///usr/bin/env java "$0" "$@" ; exit $?
// Standalone Java code (not part of main project), same jbang-friendly style as offsetgen/OffsetGen.java.

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Pattern;

/**
 * Generates a Java class of string-macro constants by asking the REAL llvm-mingw clang what each
 * macro actually expands to - the codegen answer to PRP-09's BCRYPT_HASH_LENGTH bug (a hand-typed
 * guess, "HashLength", that was plausible-but-wrong and failed with a misleading error rather than
 * "not found"). Add a name+header to winconsts.toml; there is no other way to get a value into the
 * generated file, so there is no way to hand-type a wrong one. See
 * ../../../prp/11-prp.02.codegen-safety-poc.md.
 *
 * Usage (from this directory): java WinConstGen.java [--spec winconsts.toml] [--out <path>]
 */
public class WinConstGen {

    record ConstSpec(String name, String header) {}

    private static final Pattern KV = Pattern.compile("^(\\w+)\\s*=\\s*(.+)$");

    public static void main(String[] args) throws Exception {
        var spec = Path.of("winconsts.toml");
        var out = Path.of("WinConstants.generated.java");

        for (int i = 0; i < args.length; i++) {
            switch (args[i]) {
                case "--spec" -> spec = Path.of(args[++i]);
                case "--out" -> out = Path.of(args[++i]);
                default -> throw new IllegalArgumentException("Unknown arg: " + args[i]);
            }
        }

        var specs = parseSpec(spec);
        System.out.println("Constants to generate: " + specs.stream().map(ConstSpec::name).toList());

        var sb = new StringBuilder();
        sb.append("// GENERATED by wintype-poc/constgen/WinConstGen.java - do not hand-edit.\n");
        sb.append("// Every value below came from the real compiler expanding the real macro -\n");
        sb.append("// never hand-typed. Regenerate: cd teavm-poc/wintype-poc/constgen && java WinConstGen.java\n");
        sb.append("public final class WinConstantsGenerated {\n");
        sb.append("    private WinConstantsGenerated() {}\n\n");
        for (var s : specs) {
            var value = wintype.HeaderProbe.constantValue(s.name(), s.header());
            System.out.println(s.name() + " (" + s.header() + ") = \"" + value + "\"");
            sb.append("    public static final String ").append(s.name()).append(" = \"")
                    .append(value.replace("\\", "\\\\").replace("\"", "\\\"")).append("\";\n");
        }
        sb.append("}\n");

        Files.writeString(out, sb.toString());
        System.out.println();
        System.out.println("Wrote " + out.toAbsolutePath().normalize());
    }

    private static List<ConstSpec> parseSpec(Path specPath) throws IOException {
        var out = new ArrayList<ConstSpec>();
        String name = null;
        String header = "windows.h";
        for (var raw : Files.readAllLines(specPath)) {
            var line = raw.strip();
            if (line.isEmpty() || line.startsWith("#")) {
                continue;
            }
            if (line.equals("[[wconst]]")) {
                if (name != null) {
                    out.add(new ConstSpec(name, header));
                }
                name = null;
                header = "windows.h";
                continue;
            }
            var m = KV.matcher(line);
            if (!m.matches()) {
                throw new IllegalArgumentException("Can't parse spec line in " + specPath + ": " + line);
            }
            switch (m.group(1)) {
                case "name" -> name = unquote(m.group(2));
                case "header" -> header = unquote(m.group(2));
                default -> throw new IllegalArgumentException("Unknown key in " + specPath + ": " + line);
            }
        }
        if (name != null) {
            out.add(new ConstSpec(name, header));
        }
        return out;
    }

    private static String unquote(String s) {
        s = s.strip();
        return (s.startsWith("\"") && s.endsWith("\"")) ? s.substring(1, s.length() - 1) : s;
    }
}
