// GENERATED by wintype-poc/constgen/WinConstGen.java - do not hand-edit.
// Every value below came from the real compiler expanding the real macro -
// never hand-typed. Regenerate: cd teavm-poc/wintype-poc/constgen && java WinConstGen.java
public final class WinConstantsGenerated {
    private WinConstantsGenerated() {}

    public static final String BCRYPT_OBJECT_LENGTH = "ObjectLength";
    public static final String BCRYPT_HASH_LENGTH = "HashDigestLength";
    public static final String BCRYPT_ALGORITHM_NAME = "AlgorithmName";
}
