package windemo.shim;

import org.teavm.interop.Address;
import org.teavm.interop.Import;

/** GENERATED by jextract-teavm - do not hand-edit.
 *  from byvalue-shim.h, target x86_64-w64-mingw32 (LLP64). Symbols: byvalue.symbols */
@SuppressWarnings("unused")
public final class Shim {
    private Shim() {}

    /** {@code #define JX_WindowFromPoint(1 argument)} - a function-like macro, expanded by the C compiler at the call; result: Address, 8 bytes, per clang */
    @Import(name = "JX_WindowFromPoint") public static native Address windowFromPoint(Address arg0);

    /** {@code #define JX_div(3 arguments)} - a function-like macro, expanded by the C compiler at the call; result: void, 1 bytes, per clang */
    @Import(name = "JX_div") public static native void div(int arg0, int arg1, Address arg2);

}
