package windemo.shim;

import org.teavm.interop.Address;

/** GENERATED by jextract-teavm - do not hand-edit.
 *  from byvalue-shim.h, target x86_64-w64-mingw32 (LLP64). Symbols: byvalue.symbols */
@SuppressWarnings("unused")
public final class ShimStructs {
    private ShimStructs() {}

    /** {@code struct tagPOINT} - windef.h:91, 8 bytes */
    public static final class POINT {
        private POINT() {}
        public static final int SIZE = 8;
        /** {@code LONG x} */ public static final int x = 0;
        /** {@code LONG y} */ public static final int y = 4;
        public static int x(Address s) { return s.add(x).getInt(); }
        public static void x(Address s, int v) { s.add(x).putInt(v); }
        public static int y(Address s) { return s.add(y).getInt(); }
        public static void y(Address s, int v) { s.add(y).putInt(v); }
    }

    /** {@code struct _div_t} - stdlib.h:29, 8 bytes */
    public static final class DivT {
        private DivT() {}
        public static final int SIZE = 8;
        /** {@code int quot} */ public static final int quot = 0;
        /** {@code int rem} */ public static final int rem = 4;
        public static int quot(Address s) { return s.add(quot).getInt(); }
        public static void quot(Address s, int v) { s.add(quot).putInt(v); }
        public static int rem(Address s) { return s.add(rem).getInt(); }
        public static void rem(Address s, int v) { s.add(rem).putInt(v); }
    }

}
