package littlejlib.jextract_teavm;

import module java.base;

/** Wraps generated members in a compilation unit and writes it under a source root. */
public final class JavaFile {
    public static Path write(Path srcRoot, String pkg, String cls, String provenance, Src body, List<String> imports) throws IOException {
        var src = new Src().add("package %s;", pkg).add("");
        imports.forEach(i -> src.add("import org.teavm.interop.%s;", i));
        src.add("");
        src.add("/** GENERATED by jextract-teavm - do not hand-edit.")
           .add(" *  %s */", provenance)
           .add("@SuppressWarnings(\"unused\")")
           .add("public final class %s {", cls)
           .add("    private %s() {}", cls)
           .add("")
           .addAll(body)
           .add("}");
        var file = srcRoot.resolve(pkg.replace('.', '/')).resolve(cls + ".java");
        Files.createDirectories(file.getParent());
        Files.writeString(file, src.text());
        return file;
    }
}
