#!/bin/sh
# Builds winapi.symbols from what the hand-maintained port ACTUALLY binds today, so the generated
# output can be compared name-for-name: every @Import in WinApi.java (C name + its Java name), every
# constant declared there, and every struct in offsetgen/winstructs.toml. Extras are appended by hand.
POC=../../teavm-poc
W=$POC/src/main/java/pocapp/jr/WinApi.java
{
  echo "# GENERATED by derive-symbols.sh from teavm-poc WinApi.java + winstructs.toml, then extras.symbols appended"
  echo "# --- functions (C name, Java name as hand-written) ---"
  grep -o '@Import(name = "[^"]*") static native [^(]* [a-zA-Z0-9_]*(' $W | sed -E 's/@Import\(name = "([^"]*)"\).* ([a-zA-Z0-9_]*)\($/\1 \2/'
  echo "# --- constants ---"
  grep -oE 'static final [A-Za-z]+ [A-Z_0-9]+ =' $W | awk '{print $4}'
  echo "# --- structs ---"
  grep -E '^name = ' $POC/offsetgen/winstructs.toml | sed -E 's/name = "([^"]*)"/\1/'
  cat extras.symbols
} > winapi.symbols
