/* GENERATED by jextract-teavm --verify-c: 50 assertions. */
#include <stddef.h>
#include <stdint.h>
#include "posix.h"

_Static_assert(sizeof(int) == 4, "setenv return: int");
_Static_assert(sizeof(ssize_t) == 8, "read return: ssize_t");
_Static_assert(sizeof(size_t) == 8, "read(__nbytes): size_t");
_Static_assert(sizeof(__pid_t) == 4, "fork return: __pid_t");
_Static_assert(sizeof(__mode_t) == 4, "mkdir(__mode): __mode_t");
_Static_assert(sizeof(time_t) == 8, "time return: time_t");
_Static_assert(sizeof(clockid_t) == 4, "clock_gettime(__clock_id): clockid_t");
_Static_assert((O_RDONLY) == 0LL, "O_RDONLY");
_Static_assert((O_WRONLY) == 1LL, "O_WRONLY");
_Static_assert((O_CREAT) == 64LL, "O_CREAT");
_Static_assert((O_TRUNC) == 512LL, "O_TRUNC");
_Static_assert((RTLD_NOW) == 2LL, "RTLD_NOW");
_Static_assert((PATH_MAX) == 4096LL, "PATH_MAX");
_Static_assert((F_OK) == 0LL, "F_OK");
_Static_assert((X_OK) == 1LL, "X_OK");
_Static_assert((CLOCK_MONOTONIC) == 1LL, "CLOCK_MONOTONIC");
_Static_assert((EINTR) == 4LL, "EINTR");
_Static_assert(sizeof(struct stat) == 144, "struct stat size");
_Static_assert(offsetof(struct stat, st_dev) == 0, "struct stat.st_dev");
_Static_assert(offsetof(struct stat, st_ino) == 8, "struct stat.st_ino");
_Static_assert(offsetof(struct stat, st_nlink) == 16, "struct stat.st_nlink");
_Static_assert(offsetof(struct stat, st_mode) == 24, "struct stat.st_mode");
_Static_assert(offsetof(struct stat, st_uid) == 28, "struct stat.st_uid");
_Static_assert(offsetof(struct stat, st_gid) == 32, "struct stat.st_gid");
_Static_assert(offsetof(struct stat, __pad0) == 36, "struct stat.__pad0");
_Static_assert(offsetof(struct stat, st_rdev) == 40, "struct stat.st_rdev");
_Static_assert(offsetof(struct stat, st_size) == 48, "struct stat.st_size");
_Static_assert(offsetof(struct stat, st_blksize) == 56, "struct stat.st_blksize");
_Static_assert(offsetof(struct stat, st_blocks) == 64, "struct stat.st_blocks");
_Static_assert(offsetof(struct stat, st_atim) == 72, "struct stat.st_atim");
_Static_assert(offsetof(struct stat, st_mtim) == 88, "struct stat.st_mtim");
_Static_assert(offsetof(struct stat, st_ctim) == 104, "struct stat.st_ctim");
_Static_assert(offsetof(struct stat, __glibc_reserved) == 120, "struct stat.__glibc_reserved");
_Static_assert(sizeof(struct timespec) == 16, "struct timespec size");
_Static_assert(offsetof(struct timespec, tv_sec) == 0, "struct timespec.tv_sec");
_Static_assert(offsetof(struct timespec, tv_nsec) == 8, "struct timespec.tv_nsec");
_Static_assert(sizeof(struct dirent) == 280, "struct dirent size");
_Static_assert(offsetof(struct dirent, d_ino) == 0, "struct dirent.d_ino");
_Static_assert(offsetof(struct dirent, d_off) == 8, "struct dirent.d_off");
_Static_assert(offsetof(struct dirent, d_reclen) == 16, "struct dirent.d_reclen");
_Static_assert(offsetof(struct dirent, d_type) == 18, "struct dirent.d_type");
_Static_assert(offsetof(struct dirent, d_name) == 19, "struct dirent.d_name");
_Static_assert(sizeof(S_ISDIR(((int32_t)0))) == 4, "S_ISDIR result width");
_Static_assert(__builtin_classify_type(S_ISDIR(((int32_t)0))) == 1, "S_ISDIR result type class");
_Static_assert(sizeof(S_ISREG(((int32_t)0))) == 4, "S_ISREG result width");
_Static_assert(__builtin_classify_type(S_ISREG(((int32_t)0))) == 1, "S_ISREG result type class");
_Static_assert(sizeof(WEXITSTATUS(((int32_t)0))) == 4, "WEXITSTATUS result width");
_Static_assert(__builtin_classify_type(WEXITSTATUS(((int32_t)0))) == 1, "WEXITSTATUS result type class");
_Static_assert(sizeof(WIFEXITED(((int32_t)0))) == 4, "WIFEXITED result width");
_Static_assert(__builtin_classify_type(WIFEXITED(((int32_t)0))) == 1, "WIFEXITED result type class");
