package jarrunner.jextract_teavm;

import module java.base;
import org.openjdk.jextract.*;
import org.openjdk.jextract.Declaration.*;

/**
 * Writes the generator's conclusions back out as C11 {@code _Static_assert}s - struct sizes and offsets,
 * constant values, the width of every non-pointer parameter and return type (of functions and of callback types),
 * and the result width and type class of every function-like macro - so any OTHER compiler, for the same target,
 * can check them against the same headers with {@code -fsyntax-only}. A disagreement is a build error naming the
 * symbol, not a crash at runtime.
 */
public final class CVerifier {
    final TypeMap types;
    final Src out = new Src();
    final Set<String> widthsSeen = new HashSet<>();
    int asserts;

    public CVerifier(TypeMap types) {
        this.types = types;
    }

    void check(String expr, String label) {
        out.add("_Static_assert(%s, \"%s\");", expr, label.replace("\"", "'"));
        asserts++;
    }

    public void function(Declaration.Function f) {
        width(f.type().returnType(), f.name() + " return");
        f.parameters().forEach(p -> width(p.type(), f.name() + "(" + p.name() + ")"));
    }

    public void callback(String name, Type.Function f) {
        width(f.returnType(), name + " callback return");
        for (var i = 0; i < f.argumentTypes().size(); i++) width(f.argumentTypes().get(i), name + " callback argument " + (i + 1));
    }

    /** Also fails to compile when the macro does not exist or takes another number of arguments: the typo check. */
    public void macro(MacroGen.Spec s, MacroGen.Result r) {
        if (r.classification() != 0) check("sizeof(%s) == %d".formatted(s.call(), r.size()), s.name() + " result width");
        check("__builtin_classify_type(%s) == %d".formatted(s.call(), r.classification()), s.name() + " result type class");
    }

    void width(Type t, String label) {
        var u = TypeMap.unqualified(t);
        if (u instanceof Type.Primitive p && p.kind() == Type.Primitive.Kind.Void) return;
        if (u instanceof Type.Delegated || u instanceof Type.Array) return;
        var c = TypeMap.cName(t);
        if (!widthsSeen.add(c)) return;
        check("sizeof(%s) == %d".formatted(c, types.scalarSize(t)), label + ": " + c);
    }

    public void constant(Constant c, String decodedWide) {
        switch (c.value()) {
            case Long v when types.java(c.type()).equals(TypeMap.ADDRESS) ->
                    check("(long long)(intptr_t)(%s) == %dLL".formatted(c.name(), v), c.name());
            case Long v -> check("(%s) == %s".formatted(c.name(), v == Long.MIN_VALUE ? "(-9223372036854775807LL-1)" : v + "LL"), c.name());
            case String s -> {
                var len = (decodedWide != null ? decodedWide : s).codePoints().count();
                check("sizeof(%s) / sizeof((%s)[0]) >= %d".formatted(c.name(), c.name(), len + 1), c.name() + " length");
            }
            default -> {}
        }
    }

    public void struct(Scoped s, String cSpelling, long size, List<StructGen.Field> fields) {
        check("sizeof(%s) == %d".formatted(cSpelling, size), cSpelling + " size");
        fields.forEach(f -> check("offsetof(%s, %s) == %d".formatted(cSpelling, f.name(), f.offset()), cSpelling + "." + f.name()));
    }

    /** Header paths are written relative to the verify file's own folder, so the file names no machine path. */
    public void write(Path file, List<String> headers) throws IOException {
        var src = new Src().add("/* GENERATED by jextract-teavm --verify-c: %d assertions. */", asserts)
                .add("#include <stddef.h>").add("#include <stdint.h>");
        var dir = file.toAbsolutePath().getParent();
        headers.forEach(h -> src.add(h.startsWith("<") ? "#include " + h : "#include \"" + relative(dir, Path.of(h).toAbsolutePath()) + "\""));
        Files.writeString(file, src.add("").addAll(out).text());
    }

    static String relative(Path dir, Path header) {
        try {
            return dir.relativize(header).toString().replace(File.separatorChar, '/');
        } catch (IllegalArgumentException differentDrive) {
            return header.toString().replace(File.separatorChar, '/');
        }
    }
}
