package jarrunner.jr;

import org.teavm.interop.Address;
import org.teavm.interop.Import;

/** GENERATED by jextract-teavm - do not hand-edit.
 *  from jr-posix.h, target x86_64-linux-gnu (LP64). Symbols: posix.symbols */
@SuppressWarnings("unused")
public final class PosixApi {
    private PosixApi() {}

    /** {@code extern void exit(int __status)} - stdlib.h:790 */
    @Import(name = "exit") public static native void exit(int __status);

    /** {@code extern char *getenv(const char *__name)} - stdlib.h:807 */
    @Import(name = "getenv") public static native Address getenv(Address __name);

    /** {@code extern int setenv(const char *__name, const char *__value, int __replace)} - stdlib.h:826 */
    @Import(name = "setenv") public static native int setenv(Address __name, Address __value, int __replace);

    /** {@code extern FILE *fopen(const char *restrict __filename, const char *restrict __modes)} - stdio.h:271 */
    @Import(name = "fopen") public static native Address fopen(Address __filename, Address __modes);

    /** {@code extern int fputs(const char *restrict __s, FILE *restrict __stream)} - stdio.h:711 */
    @Import(name = "fputs") public static native int fputs(Address __s, Address __stream);

    /** {@code extern int fflush(FILE *__stream)} - stdio.h:243 */
    @Import(name = "fflush") public static native int fflush(Address __stream);

    /** {@code extern int fclose(FILE *__stream)} - stdio.h:191 */
    @Import(name = "fclose") public static native int fclose(Address __stream);

    /** {@code extern unsigned long fread(void *restrict __ptr, size_t __size, size_t __n, FILE *restrict __stream)} - stdio.h:732 */
    @Import(name = "fread") public static native long fread(Address __ptr, long __size, long __n, Address __stream);

    /** {@code extern unsigned long fwrite(const void *restrict __ptr, size_t __size, size_t __n, FILE *restrict __s)} - stdio.h:739 */
    @Import(name = "fwrite") public static native long fwrite(Address __ptr, long __size, long __n, Address __s);

    /** {@code extern void *malloc(size_t __size)} - stdlib.h:682 */
    @Import(name = "malloc") public static native Address malloc(long __size);

    /** {@code extern void free(void *__ptr)} - stdlib.h:697 */
    @Import(name = "free") public static native void free(Address __ptr);

    /** {@code extern void *memset(void *__s, int __c, size_t __n)} - string.h:65 */
    @Import(name = "memset") public static native Address memset(Address __s, int __c, long __n);

    /** {@code extern time_t time(time_t *__timer)} - time.h:85 */
    @Import(name = "time") public static native long time(Address __timer);

    /** {@code extern int clock_gettime(clockid_t __clock_id, struct timespec *__tp)} - time.h:297 */
    @Import(name = "clock_gettime") public static native int clockGettime(int __clock_id, Address __tp);

    /** {@code extern int stat(const char *restrict __file, struct stat *restrict __buf)} - stat.h:205 */
    @Import(name = "stat") public static native int stat(Address __file, Address __buf);

    /** {@code extern int access(const char *__name, int __type)} - unistd.h:287 */
    @Import(name = "access") public static native int access(Address __name, int __type);

    /** {@code extern int unlink(const char *__name)} - unistd.h:858 */
    @Import(name = "unlink") public static native int unlink(Address __name);

    /** {@code extern int rename(const char *__old, const char *__new)} - stdio.h:164 */
    @Import(name = "rename") public static native int rename(Address __old, Address __new);

    /** {@code extern int mkdir(const char *__path, __mode_t __mode)} - stat.h:389 */
    @Import(name = "mkdir") public static native int mkdir(Address __path, int __mode);

    /** {@code extern int rmdir(const char *__path)} - unistd.h:867 */
    @Import(name = "rmdir") public static native int rmdir(Address __path);

    /** {@code extern DIR *opendir(const char *__name)} - dirent.h:141 */
    @Import(name = "opendir") public static native Address opendir(Address __name);

    /** {@code extern struct dirent *readdir(DIR *__dirp)} - dirent.h:164 */
    @Import(name = "readdir") public static native Address readdir(Address __dirp);

    /** {@code extern int closedir(DIR *__dirp)} - dirent.h:134 */
    @Import(name = "closedir") public static native int closedir(Address __dirp);

    /** {@code extern char *realpath(const char *restrict __name, char *restrict __resolved)} - stdlib.h:974 */
    @Import(name = "realpath") public static native Address realpath(Address __name, Address __resolved);

    /** {@code extern char *getcwd(char *__buf, size_t __size)} - unistd.h:531 */
    @Import(name = "getcwd") public static native Address getcwd(Address __buf, long __size);

    /** {@code extern int posix_spawn(pid_t *restrict __pid, const char *restrict __path, const posix_spawn_file_actions_t *restrict __file_actions, const posix_spawnattr_t *restrict __attrp, char *const __argv[], char *const __envp[])} - spawn.h:74 */
    @Import(name = "posix_spawn") public static native int posixSpawn(Address __pid, Address __path, Address __file_actions, Address __attrp, Address __argv, Address __envp);

    /** {@code extern __pid_t waitpid(__pid_t __pid, int *__stat_loc, int __options)} - wait.h:106 */
    @Import(name = "waitpid") public static native int waitpid(int __pid, Address __stat_loc, int __options);

    /** {@code extern int isatty(int __fd)} - unistd.h:809 */
    @Import(name = "isatty") public static native int isatty(int __fd);

    /** {@code extern int uname(struct utsname *__name)} - utsname.h:81 */
    @Import(name = "uname") public static native int uname(Address __name);

    /** {@code int jx_wexitstatus(int status)} - jr-posix.h:24 */
    @Import(name = "jx_wexitstatus") public static native int wexitstatus(int status);

    /** {@code int jx_wifexited(int status)} - jr-posix.h:25 */
    @Import(name = "jx_wifexited") public static native int wifexited(int status);

    /** {@code char **jx_environ()} - jr-posix.h:32 */
    @Import(name = "jx_environ") public static native Address getEnviron();

    public static final int O_RDONLY = 0; // int, fcntl-linux.h:43
    public static final int F_OK = 0; // int, unistd.h:284
    public static final int X_OK = 1; // int, unistd.h:283
    public static final int CLOCK_MONOTONIC = 1; // int, time.h:48
    public static final int PATH_MAX = 4096; // int, limits.h:13
    public static final int EINTR = 4; // int, errno-base.h:8
    public static final int DT_DIR = 4; // int, dirent.h:105
}
