<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>littlejlib.jr.poc</groupId>
  <artifactId>teavm-tcc-poc</artifactId>
  <version>1.0</version>
  <packaging>jar</packaging>
  <properties>
    <maven.compiler.source>21</maven.compiler.source>
    <maven.compiler.target>21</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <teavm.version>0.15.0</teavm.version>
  </properties>
  <dependencies>
    <dependency>
      <groupId>org.teavm</groupId>
      <artifactId>teavm-tooling</artifactId>
      <version>${teavm.version}</version>
    </dependency>
    <dependency>
      <groupId>org.teavm</groupId>
      <artifactId>teavm-classlib</artifactId>
      <version>${teavm.version}</version>
    </dependency>
  </dependencies>
</project>
