/* GENERATED by jextract-teavm --verify-c: 9 assertions. */
#include <stddef.h>
#include <stdint.h>
#include "byvalue-shim.h"

_Static_assert(sizeof(JX_WindowFromPoint((*(void**)0))) == 8, "JX_WindowFromPoint result width");
_Static_assert(__builtin_classify_type(JX_WindowFromPoint((*(void**)0))) == 5, "JX_WindowFromPoint result type class");
_Static_assert(__builtin_classify_type(JX_div((*(int32_t*)0), (*(int32_t*)0), (*(void**)0))) == 0, "JX_div result type class");
_Static_assert(sizeof(POINT) == 8, "POINT size");
_Static_assert(offsetof(POINT, x) == 0, "POINT.x");
_Static_assert(offsetof(POINT, y) == 4, "POINT.y");
_Static_assert(sizeof(div_t) == 8, "div_t size");
_Static_assert(offsetof(div_t, quot) == 0, "div_t.quot");
_Static_assert(offsetof(div_t, rem) == 4, "div_t.rem");
