/* GENERATED by jextract-teavm --verify-c: 15 assertions. */
#include <stddef.h>
#include <stdint.h>
#include "windemo.h"

_Static_assert(sizeof(WINBOOL) == 4, "EnumWindows return: WINBOOL");
_Static_assert(sizeof(LPARAM) == 8, "EnumWindows(lParam): LPARAM");
_Static_assert(sizeof(int) == 4, "WNDENUMPROC callback return: int");
_Static_assert(sizeof(long long) == 8, "WNDENUMPROC callback argument 2: long long");
_Static_assert(sizeof(unsigned int) == 4, "WNDPROC callback argument 2: unsigned int");
_Static_assert(sizeof(unsigned long long) == 8, "WNDPROC callback argument 3: unsigned long long");
_Static_assert(sizeof(size_t) == 8, "qsort(_NumOfElements): size_t");
_Static_assert(sizeof(LOWORD(((int32_t)0))) == 2, "LOWORD result width");
_Static_assert(__builtin_classify_type(LOWORD(((int32_t)0))) == 1, "LOWORD result type class");
_Static_assert(sizeof(HIWORD(((int32_t)0))) == 2, "HIWORD result width");
_Static_assert(__builtin_classify_type(HIWORD(((int32_t)0))) == 1, "HIWORD result type class");
_Static_assert(sizeof(MAKELONG(((int32_t)0), ((int32_t)0))) == 4, "MAKELONG result width");
_Static_assert(__builtin_classify_type(MAKELONG(((int32_t)0), ((int32_t)0))) == 1, "MAKELONG result type class");
_Static_assert(sizeof(MAKELPARAM(((int32_t)0), ((int32_t)0))) == 8, "MAKELPARAM result width");
_Static_assert(__builtin_classify_type(MAKELPARAM(((int32_t)0), ((int32_t)0))) == 1, "MAKELPARAM result type class");
