/* GENERATED by jextract-teavm --verify-c: 53 assertions. */
#include <stddef.h>
#include <stdint.h>
#include "jr-posix-macos.h"

_Static_assert(sizeof(int) == 4, "exit(): int");
_Static_assert(sizeof(unsigned long) == 8, "fread return: unsigned long");
_Static_assert(sizeof(size_t) == 8, "fread(__size): size_t");
_Static_assert(sizeof(ssize_t) == 8, "write return: ssize_t");
_Static_assert(sizeof(time_t) == 8, "time return: time_t");
_Static_assert(sizeof(clockid_t) == 4, "clock_gettime(__clock_id): clockid_t");
_Static_assert(sizeof(mode_t) == 2, "chmod(): mode_t");
_Static_assert(sizeof(pid_t) == 4, "waitpid return: pid_t");
_Static_assert((O_RDONLY) == 0LL, "O_RDONLY");
_Static_assert((F_OK) == 0LL, "F_OK");
_Static_assert((X_OK) == 1LL, "X_OK");
_Static_assert((W_OK) == 2LL, "W_OK");
_Static_assert((CLOCK_MONOTONIC) == 6LL, "CLOCK_MONOTONIC");
_Static_assert((PATH_MAX) == 1024LL, "PATH_MAX");
_Static_assert((EINTR) == 4LL, "EINTR");
_Static_assert((DT_DIR) == 4LL, "DT_DIR");
_Static_assert((RTLD_NOW) == 2LL, "RTLD_NOW");
_Static_assert(sizeof(struct stat) == 144, "struct stat size");
_Static_assert(offsetof(struct stat, st_dev) == 0, "struct stat.st_dev");
_Static_assert(offsetof(struct stat, st_mode) == 4, "struct stat.st_mode");
_Static_assert(offsetof(struct stat, st_nlink) == 6, "struct stat.st_nlink");
_Static_assert(offsetof(struct stat, st_ino) == 8, "struct stat.st_ino");
_Static_assert(offsetof(struct stat, st_uid) == 16, "struct stat.st_uid");
_Static_assert(offsetof(struct stat, st_gid) == 20, "struct stat.st_gid");
_Static_assert(offsetof(struct stat, st_rdev) == 24, "struct stat.st_rdev");
_Static_assert(offsetof(struct stat, st_atimespec) == 32, "struct stat.st_atimespec");
_Static_assert(offsetof(struct stat, st_mtimespec) == 48, "struct stat.st_mtimespec");
_Static_assert(offsetof(struct stat, st_ctimespec) == 64, "struct stat.st_ctimespec");
_Static_assert(offsetof(struct stat, st_birthtimespec) == 80, "struct stat.st_birthtimespec");
_Static_assert(offsetof(struct stat, st_size) == 96, "struct stat.st_size");
_Static_assert(offsetof(struct stat, st_blocks) == 104, "struct stat.st_blocks");
_Static_assert(offsetof(struct stat, st_blksize) == 112, "struct stat.st_blksize");
_Static_assert(offsetof(struct stat, st_flags) == 116, "struct stat.st_flags");
_Static_assert(offsetof(struct stat, st_gen) == 120, "struct stat.st_gen");
_Static_assert(offsetof(struct stat, st_lspare) == 124, "struct stat.st_lspare");
_Static_assert(offsetof(struct stat, st_qspare) == 128, "struct stat.st_qspare");
_Static_assert(sizeof(struct timespec) == 16, "struct timespec size");
_Static_assert(offsetof(struct timespec, tv_sec) == 0, "struct timespec.tv_sec");
_Static_assert(offsetof(struct timespec, tv_nsec) == 8, "struct timespec.tv_nsec");
_Static_assert(sizeof(struct dirent) == 1048, "struct dirent size");
_Static_assert(offsetof(struct dirent, d_ino) == 0, "struct dirent.d_ino");
_Static_assert(offsetof(struct dirent, d_seekoff) == 8, "struct dirent.d_seekoff");
_Static_assert(offsetof(struct dirent, d_reclen) == 16, "struct dirent.d_reclen");
_Static_assert(offsetof(struct dirent, d_namlen) == 18, "struct dirent.d_namlen");
_Static_assert(offsetof(struct dirent, d_type) == 20, "struct dirent.d_type");
_Static_assert(offsetof(struct dirent, d_name) == 21, "struct dirent.d_name");
_Static_assert(sizeof(struct utsname) == 1280, "struct utsname size");
_Static_assert(offsetof(struct utsname, sysname) == 0, "struct utsname.sysname");
_Static_assert(offsetof(struct utsname, nodename) == 256, "struct utsname.nodename");
_Static_assert(offsetof(struct utsname, release) == 512, "struct utsname.release");
_Static_assert(offsetof(struct utsname, version) == 768, "struct utsname.version");
_Static_assert(offsetof(struct utsname, machine) == 1024, "struct utsname.machine");
_Static_assert(sizeof(uint32_t) == 4, "_dyld_get_image_header(image_index): uint32_t");
