package pocapp.jr;

import org.teavm.interop.Address;

/** GENERATED by jextract-teavm - do not hand-edit.
 *  from jr.h, target aarch64-w64-mingw32 (LLP64). Symbols: winapi.symbols */
@SuppressWarnings("unused")
public final class WinOffsets {
    private WinOffsets() {}

    /** {@code struct _FILETIME} - minwindef.h:222, 8 bytes */
    public static final class FILETIME {
        private FILETIME() {}
        public static final int SIZE = 8;
        /** {@code DWORD dwLowDateTime} */ public static final int dwLowDateTime = 0;
        /** {@code DWORD dwHighDateTime} */ public static final int dwHighDateTime = 4;
        public static int dwLowDateTime(Address s) { return s.add(dwLowDateTime).getInt(); }
        public static void dwLowDateTime(Address s, int v) { s.add(dwLowDateTime).putInt(v); }
        public static int dwHighDateTime(Address s) { return s.add(dwHighDateTime).getInt(); }
        public static void dwHighDateTime(Address s, int v) { s.add(dwHighDateTime).putInt(v); }
    }

    /** {@code struct _WIN32_FILE_ATTRIBUTE_DATA} - fileapi.h:154, 36 bytes */
    public static final class WIN32_FILE_ATTRIBUTE_DATA {
        private WIN32_FILE_ATTRIBUTE_DATA() {}
        public static final int SIZE = 36;
        /** {@code DWORD dwFileAttributes} */ public static final int dwFileAttributes = 0;
        /** {@code FILETIME ftCreationTime} */ public static final int ftCreationTime = 4;
        /** {@code FILETIME ftLastAccessTime} */ public static final int ftLastAccessTime = 12;
        /** {@code FILETIME ftLastWriteTime} */ public static final int ftLastWriteTime = 20;
        /** {@code DWORD nFileSizeHigh} */ public static final int nFileSizeHigh = 28;
        /** {@code DWORD nFileSizeLow} */ public static final int nFileSizeLow = 32;
        public static int dwFileAttributes(Address s) { return s.add(dwFileAttributes).getInt(); }
        public static void dwFileAttributes(Address s, int v) { s.add(dwFileAttributes).putInt(v); }
        public static int nFileSizeHigh(Address s) { return s.add(nFileSizeHigh).getInt(); }
        public static void nFileSizeHigh(Address s, int v) { s.add(nFileSizeHigh).putInt(v); }
        public static int nFileSizeLow(Address s) { return s.add(nFileSizeLow).getInt(); }
        public static void nFileSizeLow(Address s, int v) { s.add(nFileSizeLow).putInt(v); }
    }

    /** {@code struct _STARTUPINFOA} - processthreadsapi.h:51, 104 bytes */
    public static final class STARTUPINFOA {
        private STARTUPINFOA() {}
        public static final int SIZE = 104;
        /** {@code DWORD cb} */ public static final int cb = 0;
        /** {@code LPSTR lpReserved} */ public static final int lpReserved = 8;
        /** {@code LPSTR lpDesktop} */ public static final int lpDesktop = 16;
        /** {@code LPSTR lpTitle} */ public static final int lpTitle = 24;
        /** {@code DWORD dwX} */ public static final int dwX = 32;
        /** {@code DWORD dwY} */ public static final int dwY = 36;
        /** {@code DWORD dwXSize} */ public static final int dwXSize = 40;
        /** {@code DWORD dwYSize} */ public static final int dwYSize = 44;
        /** {@code DWORD dwXCountChars} */ public static final int dwXCountChars = 48;
        /** {@code DWORD dwYCountChars} */ public static final int dwYCountChars = 52;
        /** {@code DWORD dwFillAttribute} */ public static final int dwFillAttribute = 56;
        /** {@code DWORD dwFlags} */ public static final int dwFlags = 60;
        /** {@code WORD wShowWindow} */ public static final int wShowWindow = 64;
        /** {@code WORD cbReserved2} */ public static final int cbReserved2 = 66;
        /** {@code LPBYTE lpReserved2} */ public static final int lpReserved2 = 72;
        /** {@code HANDLE hStdInput} */ public static final int hStdInput = 80;
        /** {@code HANDLE hStdOutput} */ public static final int hStdOutput = 88;
        /** {@code HANDLE hStdError} */ public static final int hStdError = 96;
        public static int cb(Address s) { return s.add(cb).getInt(); }
        public static void cb(Address s, int v) { s.add(cb).putInt(v); }
        public static Address lpReserved(Address s) { return s.add(lpReserved).getAddress(); }
        public static void lpReserved(Address s, Address v) { s.add(lpReserved).putAddress(v); }
        public static Address lpDesktop(Address s) { return s.add(lpDesktop).getAddress(); }
        public static void lpDesktop(Address s, Address v) { s.add(lpDesktop).putAddress(v); }
        public static Address lpTitle(Address s) { return s.add(lpTitle).getAddress(); }
        public static void lpTitle(Address s, Address v) { s.add(lpTitle).putAddress(v); }
        public static int dwX(Address s) { return s.add(dwX).getInt(); }
        public static void dwX(Address s, int v) { s.add(dwX).putInt(v); }
        public static int dwY(Address s) { return s.add(dwY).getInt(); }
        public static void dwY(Address s, int v) { s.add(dwY).putInt(v); }
        public static int dwXSize(Address s) { return s.add(dwXSize).getInt(); }
        public static void dwXSize(Address s, int v) { s.add(dwXSize).putInt(v); }
        public static int dwYSize(Address s) { return s.add(dwYSize).getInt(); }
        public static void dwYSize(Address s, int v) { s.add(dwYSize).putInt(v); }
        public static int dwXCountChars(Address s) { return s.add(dwXCountChars).getInt(); }
        public static void dwXCountChars(Address s, int v) { s.add(dwXCountChars).putInt(v); }
        public static int dwYCountChars(Address s) { return s.add(dwYCountChars).getInt(); }
        public static void dwYCountChars(Address s, int v) { s.add(dwYCountChars).putInt(v); }
        public static int dwFillAttribute(Address s) { return s.add(dwFillAttribute).getInt(); }
        public static void dwFillAttribute(Address s, int v) { s.add(dwFillAttribute).putInt(v); }
        public static int dwFlags(Address s) { return s.add(dwFlags).getInt(); }
        public static void dwFlags(Address s, int v) { s.add(dwFlags).putInt(v); }
        public static short wShowWindow(Address s) { return s.add(wShowWindow).getShort(); }
        public static void wShowWindow(Address s, short v) { s.add(wShowWindow).putShort(v); }
        public static short cbReserved2(Address s) { return s.add(cbReserved2).getShort(); }
        public static void cbReserved2(Address s, short v) { s.add(cbReserved2).putShort(v); }
        public static Address lpReserved2(Address s) { return s.add(lpReserved2).getAddress(); }
        public static void lpReserved2(Address s, Address v) { s.add(lpReserved2).putAddress(v); }
        public static Address hStdInput(Address s) { return s.add(hStdInput).getAddress(); }
        public static void hStdInput(Address s, Address v) { s.add(hStdInput).putAddress(v); }
        public static Address hStdOutput(Address s) { return s.add(hStdOutput).getAddress(); }
        public static void hStdOutput(Address s, Address v) { s.add(hStdOutput).putAddress(v); }
        public static Address hStdError(Address s) { return s.add(hStdError).getAddress(); }
        public static void hStdError(Address s, Address v) { s.add(hStdError).putAddress(v); }
    }

    /** {@code struct _PROCESS_INFORMATION} - processthreadsapi.h:96, 24 bytes */
    public static final class PROCESS_INFORMATION {
        private PROCESS_INFORMATION() {}
        public static final int SIZE = 24;
        /** {@code HANDLE hProcess} */ public static final int hProcess = 0;
        /** {@code HANDLE hThread} */ public static final int hThread = 8;
        /** {@code DWORD dwProcessId} */ public static final int dwProcessId = 16;
        /** {@code DWORD dwThreadId} */ public static final int dwThreadId = 20;
        public static Address hProcess(Address s) { return s.add(hProcess).getAddress(); }
        public static void hProcess(Address s, Address v) { s.add(hProcess).putAddress(v); }
        public static Address hThread(Address s) { return s.add(hThread).getAddress(); }
        public static void hThread(Address s, Address v) { s.add(hThread).putAddress(v); }
        public static int dwProcessId(Address s) { return s.add(dwProcessId).getInt(); }
        public static void dwProcessId(Address s, int v) { s.add(dwProcessId).putInt(v); }
        public static int dwThreadId(Address s) { return s.add(dwThreadId).getInt(); }
        public static void dwThreadId(Address s, int v) { s.add(dwThreadId).putInt(v); }
    }

    /** {@code struct _WIN32_FIND_DATAA} - minwinbase.h:61, 320 bytes */
    public static final class WIN32_FIND_DATAA {
        private WIN32_FIND_DATAA() {}
        public static final int SIZE = 320;
        /** {@code DWORD dwFileAttributes} */ public static final int dwFileAttributes = 0;
        /** {@code FILETIME ftCreationTime} */ public static final int ftCreationTime = 4;
        /** {@code FILETIME ftLastAccessTime} */ public static final int ftLastAccessTime = 12;
        /** {@code FILETIME ftLastWriteTime} */ public static final int ftLastWriteTime = 20;
        /** {@code DWORD nFileSizeHigh} */ public static final int nFileSizeHigh = 28;
        /** {@code DWORD nFileSizeLow} */ public static final int nFileSizeLow = 32;
        /** {@code DWORD dwReserved0} */ public static final int dwReserved0 = 36;
        /** {@code DWORD dwReserved1} */ public static final int dwReserved1 = 40;
        /** {@code CHAR[260] cFileName} */ public static final int cFileName = 44;
        /** {@code CHAR[14] cAlternateFileName} */ public static final int cAlternateFileName = 304;
        public static int dwFileAttributes(Address s) { return s.add(dwFileAttributes).getInt(); }
        public static void dwFileAttributes(Address s, int v) { s.add(dwFileAttributes).putInt(v); }
        public static int nFileSizeHigh(Address s) { return s.add(nFileSizeHigh).getInt(); }
        public static void nFileSizeHigh(Address s, int v) { s.add(nFileSizeHigh).putInt(v); }
        public static int nFileSizeLow(Address s) { return s.add(nFileSizeLow).getInt(); }
        public static void nFileSizeLow(Address s, int v) { s.add(nFileSizeLow).putInt(v); }
        public static int dwReserved0(Address s) { return s.add(dwReserved0).getInt(); }
        public static void dwReserved0(Address s, int v) { s.add(dwReserved0).putInt(v); }
        public static int dwReserved1(Address s) { return s.add(dwReserved1).getInt(); }
        public static void dwReserved1(Address s, int v) { s.add(dwReserved1).putInt(v); }
    }

    /** {@code struct tagMSG} - winuser.h:955, 48 bytes */
    public static final class MSG {
        private MSG() {}
        public static final int SIZE = 48;
        /** {@code HWND hwnd} */ public static final int hwnd = 0;
        /** {@code UINT message} */ public static final int message = 8;
        /** {@code WPARAM wParam} */ public static final int wParam = 16;
        /** {@code LPARAM lParam} */ public static final int lParam = 24;
        /** {@code DWORD time} */ public static final int time = 32;
        /** {@code POINT pt} */ public static final int pt = 36;
        public static Address hwnd(Address s) { return s.add(hwnd).getAddress(); }
        public static void hwnd(Address s, Address v) { s.add(hwnd).putAddress(v); }
        public static int message(Address s) { return s.add(message).getInt(); }
        public static void message(Address s, int v) { s.add(message).putInt(v); }
        public static long wParam(Address s) { return s.add(wParam).getLong(); }
        public static void wParam(Address s, long v) { s.add(wParam).putLong(v); }
        public static long lParam(Address s) { return s.add(lParam).getLong(); }
        public static void lParam(Address s, long v) { s.add(lParam).putLong(v); }
        public static int time(Address s) { return s.add(time).getInt(); }
        public static void time(Address s, int v) { s.add(time).putInt(v); }
    }

}
