package littlejlib.jr;

import org.teavm.interop.Address;

/** GENERATED by jextract-teavm - do not hand-edit.
 *  from jr.h, target x86_64-w64-mingw32 (LLP64). Symbols: winapi.symbols */
@SuppressWarnings("unused")
public final class WinOffsets {
    private WinOffsets() {}

    /** {@code struct _FILETIME} - minwindef.h:222, 8 bytes */
    public static final class FILETIME {
        private FILETIME() {}
        public static final int SIZE = 8;
        /** {@code DWORD dwLowDateTime} */ public static final int dwLowDateTime = 0;
        /** {@code DWORD dwHighDateTime} */ public static final int dwHighDateTime = 4;
        public static int dwLowDateTime(Address s) { return s.add(dwLowDateTime).getInt(); }
        public static void dwLowDateTime(Address s, int v) { s.add(dwLowDateTime).putInt(v); }
        public static int dwHighDateTime(Address s) { return s.add(dwHighDateTime).getInt(); }
        public static void dwHighDateTime(Address s, int v) { s.add(dwHighDateTime).putInt(v); }
    }

    /** {@code struct _WIN32_FILE_ATTRIBUTE_DATA} - fileapi.h:154, 36 bytes */
    public static final class WIN32_FILE_ATTRIBUTE_DATA {
        private WIN32_FILE_ATTRIBUTE_DATA() {}
        public static final int SIZE = 36;
        /** {@code DWORD dwFileAttributes} */ public static final int dwFileAttributes = 0;
        /** {@code FILETIME ftCreationTime} */ public static final int ftCreationTime = 4;
        /** {@code FILETIME ftLastAccessTime} */ public static final int ftLastAccessTime = 12;
        /** {@code FILETIME ftLastWriteTime} */ public static final int ftLastWriteTime = 20;
        /** {@code DWORD nFileSizeHigh} */ public static final int nFileSizeHigh = 28;
        /** {@code DWORD nFileSizeLow} */ public static final int nFileSizeLow = 32;
        public static int dwFileAttributes(Address s) { return s.add(dwFileAttributes).getInt(); }
        public static void dwFileAttributes(Address s, int v) { s.add(dwFileAttributes).putInt(v); }
        public static int nFileSizeHigh(Address s) { return s.add(nFileSizeHigh).getInt(); }
        public static void nFileSizeHigh(Address s, int v) { s.add(nFileSizeHigh).putInt(v); }
        public static int nFileSizeLow(Address s) { return s.add(nFileSizeLow).getInt(); }
        public static void nFileSizeLow(Address s, int v) { s.add(nFileSizeLow).putInt(v); }
    }

    /** {@code struct _STARTUPINFOA} - processthreadsapi.h:51, 104 bytes */
    public static final class STARTUPINFOA {
        private STARTUPINFOA() {}
        public static final int SIZE = 104;
        /** {@code DWORD cb} */ public static final int cb = 0;
        /** {@code LPSTR lpReserved} */ public static final int lpReserved = 8;
        /** {@code LPSTR lpDesktop} */ public static final int lpDesktop = 16;
        /** {@code LPSTR lpTitle} */ public static final int lpTitle = 24;
        /** {@code DWORD dwX} */ public static final int dwX = 32;
        /** {@code DWORD dwY} */ public static final int dwY = 36;
        /** {@code DWORD dwXSize} */ public static final int dwXSize = 40;
        /** {@code DWORD dwYSize} */ public static final int dwYSize = 44;
        /** {@code DWORD dwXCountChars} */ public static final int dwXCountChars = 48;
        /** {@code DWORD dwYCountChars} */ public static final int dwYCountChars = 52;
        /** {@code DWORD dwFillAttribute} */ public static final int dwFillAttribute = 56;
        /** {@code DWORD dwFlags} */ public static final int dwFlags = 60;
        /** {@code WORD wShowWindow} */ public static final int wShowWindow = 64;
        /** {@code WORD cbReserved2} */ public static final int cbReserved2 = 66;
        /** {@code LPBYTE lpReserved2} */ public static final int lpReserved2 = 72;
        /** {@code HANDLE hStdInput} */ public static final int hStdInput = 80;
        /** {@code HANDLE hStdOutput} */ public static final int hStdOutput = 88;
        /** {@code HANDLE hStdError} */ public static final int hStdError = 96;
        public static int cb(Address s) { return s.add(cb).getInt(); }
        public static void cb(Address s, int v) { s.add(cb).putInt(v); }
        public static Address lpReserved(Address s) { return s.add(lpReserved).getAddress(); }
        public static void lpReserved(Address s, Address v) { s.add(lpReserved).putAddress(v); }
        public static Address lpDesktop(Address s) { return s.add(lpDesktop).getAddress(); }
        public static void lpDesktop(Address s, Address v) { s.add(lpDesktop).putAddress(v); }
        public static Address lpTitle(Address s) { return s.add(lpTitle).getAddress(); }
        public static void lpTitle(Address s, Address v) { s.add(lpTitle).putAddress(v); }
        public static int dwX(Address s) { return s.add(dwX).getInt(); }
        public static void dwX(Address s, int v) { s.add(dwX).putInt(v); }
        public static int dwY(Address s) { return s.add(dwY).getInt(); }
        public static void dwY(Address s, int v) { s.add(dwY).putInt(v); }
        public static int dwXSize(Address s) { return s.add(dwXSize).getInt(); }
        public static void dwXSize(Address s, int v) { s.add(dwXSize).putInt(v); }
        public static int dwYSize(Address s) { return s.add(dwYSize).getInt(); }
        public static void dwYSize(Address s, int v) { s.add(dwYSize).putInt(v); }
        public static int dwXCountChars(Address s) { return s.add(dwXCountChars).getInt(); }
        public static void dwXCountChars(Address s, int v) { s.add(dwXCountChars).putInt(v); }
        public static int dwYCountChars(Address s) { return s.add(dwYCountChars).getInt(); }
        public static void dwYCountChars(Address s, int v) { s.add(dwYCountChars).putInt(v); }
        public static int dwFillAttribute(Address s) { return s.add(dwFillAttribute).getInt(); }
        public static void dwFillAttribute(Address s, int v) { s.add(dwFillAttribute).putInt(v); }
        public static int dwFlags(Address s) { return s.add(dwFlags).getInt(); }
        public static void dwFlags(Address s, int v) { s.add(dwFlags).putInt(v); }
        public static short wShowWindow(Address s) { return s.add(wShowWindow).getShort(); }
        public static void wShowWindow(Address s, short v) { s.add(wShowWindow).putShort(v); }
        public static short cbReserved2(Address s) { return s.add(cbReserved2).getShort(); }
        public static void cbReserved2(Address s, short v) { s.add(cbReserved2).putShort(v); }
        public static Address lpReserved2(Address s) { return s.add(lpReserved2).getAddress(); }
        public static void lpReserved2(Address s, Address v) { s.add(lpReserved2).putAddress(v); }
        public static Address hStdInput(Address s) { return s.add(hStdInput).getAddress(); }
        public static void hStdInput(Address s, Address v) { s.add(hStdInput).putAddress(v); }
        public static Address hStdOutput(Address s) { return s.add(hStdOutput).getAddress(); }
        public static void hStdOutput(Address s, Address v) { s.add(hStdOutput).putAddress(v); }
        public static Address hStdError(Address s) { return s.add(hStdError).getAddress(); }
        public static void hStdError(Address s, Address v) { s.add(hStdError).putAddress(v); }
    }

    /** {@code struct _PROCESS_INFORMATION} - processthreadsapi.h:96, 24 bytes */
    public static final class PROCESS_INFORMATION {
        private PROCESS_INFORMATION() {}
        public static final int SIZE = 24;
        /** {@code HANDLE hProcess} */ public static final int hProcess = 0;
        /** {@code HANDLE hThread} */ public static final int hThread = 8;
        /** {@code DWORD dwProcessId} */ public static final int dwProcessId = 16;
        /** {@code DWORD dwThreadId} */ public static final int dwThreadId = 20;
        public static Address hProcess(Address s) { return s.add(hProcess).getAddress(); }
        public static void hProcess(Address s, Address v) { s.add(hProcess).putAddress(v); }
        public static Address hThread(Address s) { return s.add(hThread).getAddress(); }
        public static void hThread(Address s, Address v) { s.add(hThread).putAddress(v); }
        public static int dwProcessId(Address s) { return s.add(dwProcessId).getInt(); }
        public static void dwProcessId(Address s, int v) { s.add(dwProcessId).putInt(v); }
        public static int dwThreadId(Address s) { return s.add(dwThreadId).getInt(); }
        public static void dwThreadId(Address s, int v) { s.add(dwThreadId).putInt(v); }
    }

    /** {@code struct _WIN32_FIND_DATAA} - minwinbase.h:61, 320 bytes */
    public static final class WIN32_FIND_DATAA {
        private WIN32_FIND_DATAA() {}
        public static final int SIZE = 320;
        /** {@code DWORD dwFileAttributes} */ public static final int dwFileAttributes = 0;
        /** {@code FILETIME ftCreationTime} */ public static final int ftCreationTime = 4;
        /** {@code FILETIME ftLastAccessTime} */ public static final int ftLastAccessTime = 12;
        /** {@code FILETIME ftLastWriteTime} */ public static final int ftLastWriteTime = 20;
        /** {@code DWORD nFileSizeHigh} */ public static final int nFileSizeHigh = 28;
        /** {@code DWORD nFileSizeLow} */ public static final int nFileSizeLow = 32;
        /** {@code DWORD dwReserved0} */ public static final int dwReserved0 = 36;
        /** {@code DWORD dwReserved1} */ public static final int dwReserved1 = 40;
        /** {@code CHAR[260] cFileName} */ public static final int cFileName = 44;
        /** {@code CHAR[14] cAlternateFileName} */ public static final int cAlternateFileName = 304;
        public static int dwFileAttributes(Address s) { return s.add(dwFileAttributes).getInt(); }
        public static void dwFileAttributes(Address s, int v) { s.add(dwFileAttributes).putInt(v); }
        public static int nFileSizeHigh(Address s) { return s.add(nFileSizeHigh).getInt(); }
        public static void nFileSizeHigh(Address s, int v) { s.add(nFileSizeHigh).putInt(v); }
        public static int nFileSizeLow(Address s) { return s.add(nFileSizeLow).getInt(); }
        public static void nFileSizeLow(Address s, int v) { s.add(nFileSizeLow).putInt(v); }
        public static int dwReserved0(Address s) { return s.add(dwReserved0).getInt(); }
        public static void dwReserved0(Address s, int v) { s.add(dwReserved0).putInt(v); }
        public static int dwReserved1(Address s) { return s.add(dwReserved1).getInt(); }
        public static void dwReserved1(Address s, int v) { s.add(dwReserved1).putInt(v); }
    }

    /** {@code struct tagMSG} - winuser.h:955, 48 bytes */
    public static final class MSG {
        private MSG() {}
        public static final int SIZE = 48;
        /** {@code HWND hwnd} */ public static final int hwnd = 0;
        /** {@code UINT message} */ public static final int message = 8;
        /** {@code WPARAM wParam} */ public static final int wParam = 16;
        /** {@code LPARAM lParam} */ public static final int lParam = 24;
        /** {@code DWORD time} */ public static final int time = 32;
        /** {@code POINT pt} */ public static final int pt = 36;
        public static Address hwnd(Address s) { return s.add(hwnd).getAddress(); }
        public static void hwnd(Address s, Address v) { s.add(hwnd).putAddress(v); }
        public static int message(Address s) { return s.add(message).getInt(); }
        public static void message(Address s, int v) { s.add(message).putInt(v); }
        public static long wParam(Address s) { return s.add(wParam).getLong(); }
        public static void wParam(Address s, long v) { s.add(wParam).putLong(v); }
        public static long lParam(Address s) { return s.add(lParam).getLong(); }
        public static void lParam(Address s, long v) { s.add(lParam).putLong(v); }
        public static int time(Address s) { return s.add(time).getInt(); }
        public static void time(Address s, int v) { s.add(time).putInt(v); }
    }

    /** {@code struct tagVS_FIXEDFILEINFO} - winver.h:118, 52 bytes */
    public static final class VS_FIXEDFILEINFO {
        private VS_FIXEDFILEINFO() {}
        public static final int SIZE = 52;
        /** {@code DWORD dwSignature} */ public static final int dwSignature = 0;
        /** {@code DWORD dwStrucVersion} */ public static final int dwStrucVersion = 4;
        /** {@code DWORD dwFileVersionMS} */ public static final int dwFileVersionMS = 8;
        /** {@code DWORD dwFileVersionLS} */ public static final int dwFileVersionLS = 12;
        /** {@code DWORD dwProductVersionMS} */ public static final int dwProductVersionMS = 16;
        /** {@code DWORD dwProductVersionLS} */ public static final int dwProductVersionLS = 20;
        /** {@code DWORD dwFileFlagsMask} */ public static final int dwFileFlagsMask = 24;
        /** {@code DWORD dwFileFlags} */ public static final int dwFileFlags = 28;
        /** {@code DWORD dwFileOS} */ public static final int dwFileOS = 32;
        /** {@code DWORD dwFileType} */ public static final int dwFileType = 36;
        /** {@code DWORD dwFileSubtype} */ public static final int dwFileSubtype = 40;
        /** {@code DWORD dwFileDateMS} */ public static final int dwFileDateMS = 44;
        /** {@code DWORD dwFileDateLS} */ public static final int dwFileDateLS = 48;
        public static int dwSignature(Address s) { return s.add(dwSignature).getInt(); }
        public static void dwSignature(Address s, int v) { s.add(dwSignature).putInt(v); }
        public static int dwStrucVersion(Address s) { return s.add(dwStrucVersion).getInt(); }
        public static void dwStrucVersion(Address s, int v) { s.add(dwStrucVersion).putInt(v); }
        public static int dwFileVersionMS(Address s) { return s.add(dwFileVersionMS).getInt(); }
        public static void dwFileVersionMS(Address s, int v) { s.add(dwFileVersionMS).putInt(v); }
        public static int dwFileVersionLS(Address s) { return s.add(dwFileVersionLS).getInt(); }
        public static void dwFileVersionLS(Address s, int v) { s.add(dwFileVersionLS).putInt(v); }
        public static int dwProductVersionMS(Address s) { return s.add(dwProductVersionMS).getInt(); }
        public static void dwProductVersionMS(Address s, int v) { s.add(dwProductVersionMS).putInt(v); }
        public static int dwProductVersionLS(Address s) { return s.add(dwProductVersionLS).getInt(); }
        public static void dwProductVersionLS(Address s, int v) { s.add(dwProductVersionLS).putInt(v); }
        public static int dwFileFlagsMask(Address s) { return s.add(dwFileFlagsMask).getInt(); }
        public static void dwFileFlagsMask(Address s, int v) { s.add(dwFileFlagsMask).putInt(v); }
        public static int dwFileFlags(Address s) { return s.add(dwFileFlags).getInt(); }
        public static void dwFileFlags(Address s, int v) { s.add(dwFileFlags).putInt(v); }
        public static int dwFileOS(Address s) { return s.add(dwFileOS).getInt(); }
        public static void dwFileOS(Address s, int v) { s.add(dwFileOS).putInt(v); }
        public static int dwFileType(Address s) { return s.add(dwFileType).getInt(); }
        public static void dwFileType(Address s, int v) { s.add(dwFileType).putInt(v); }
        public static int dwFileSubtype(Address s) { return s.add(dwFileSubtype).getInt(); }
        public static void dwFileSubtype(Address s, int v) { s.add(dwFileSubtype).putInt(v); }
        public static int dwFileDateMS(Address s) { return s.add(dwFileDateMS).getInt(); }
        public static void dwFileDateMS(Address s, int v) { s.add(dwFileDateMS).putInt(v); }
        public static int dwFileDateLS(Address s) { return s.add(dwFileDateLS).getInt(); }
        public static void dwFileDateLS(Address s, int v) { s.add(dwFileDateLS).putInt(v); }
    }

    /** {@code struct _IMAGE_DOS_HEADER} - winnt.h:7436, 64 bytes */
    public static final class IMAGE_DOS_HEADER {
        private IMAGE_DOS_HEADER() {}
        public static final int SIZE = 64;
        /** {@code WORD e_magic} */ public static final int e_magic = 0;
        /** {@code WORD e_cblp} */ public static final int e_cblp = 2;
        /** {@code WORD e_cp} */ public static final int e_cp = 4;
        /** {@code WORD e_crlc} */ public static final int e_crlc = 6;
        /** {@code WORD e_cparhdr} */ public static final int e_cparhdr = 8;
        /** {@code WORD e_minalloc} */ public static final int e_minalloc = 10;
        /** {@code WORD e_maxalloc} */ public static final int e_maxalloc = 12;
        /** {@code WORD e_ss} */ public static final int e_ss = 14;
        /** {@code WORD e_sp} */ public static final int e_sp = 16;
        /** {@code WORD e_csum} */ public static final int e_csum = 18;
        /** {@code WORD e_ip} */ public static final int e_ip = 20;
        /** {@code WORD e_cs} */ public static final int e_cs = 22;
        /** {@code WORD e_lfarlc} */ public static final int e_lfarlc = 24;
        /** {@code WORD e_ovno} */ public static final int e_ovno = 26;
        /** {@code WORD[4] e_res} */ public static final int e_res = 28;
        /** {@code WORD e_oemid} */ public static final int e_oemid = 36;
        /** {@code WORD e_oeminfo} */ public static final int e_oeminfo = 38;
        /** {@code WORD[10] e_res2} */ public static final int e_res2 = 40;
        /** {@code LONG e_lfanew} */ public static final int e_lfanew = 60;
        public static short e_magic(Address s) { return s.add(e_magic).getShort(); }
        public static void e_magic(Address s, short v) { s.add(e_magic).putShort(v); }
        public static short e_cblp(Address s) { return s.add(e_cblp).getShort(); }
        public static void e_cblp(Address s, short v) { s.add(e_cblp).putShort(v); }
        public static short e_cp(Address s) { return s.add(e_cp).getShort(); }
        public static void e_cp(Address s, short v) { s.add(e_cp).putShort(v); }
        public static short e_crlc(Address s) { return s.add(e_crlc).getShort(); }
        public static void e_crlc(Address s, short v) { s.add(e_crlc).putShort(v); }
        public static short e_cparhdr(Address s) { return s.add(e_cparhdr).getShort(); }
        public static void e_cparhdr(Address s, short v) { s.add(e_cparhdr).putShort(v); }
        public static short e_minalloc(Address s) { return s.add(e_minalloc).getShort(); }
        public static void e_minalloc(Address s, short v) { s.add(e_minalloc).putShort(v); }
        public static short e_maxalloc(Address s) { return s.add(e_maxalloc).getShort(); }
        public static void e_maxalloc(Address s, short v) { s.add(e_maxalloc).putShort(v); }
        public static short e_ss(Address s) { return s.add(e_ss).getShort(); }
        public static void e_ss(Address s, short v) { s.add(e_ss).putShort(v); }
        public static short e_sp(Address s) { return s.add(e_sp).getShort(); }
        public static void e_sp(Address s, short v) { s.add(e_sp).putShort(v); }
        public static short e_csum(Address s) { return s.add(e_csum).getShort(); }
        public static void e_csum(Address s, short v) { s.add(e_csum).putShort(v); }
        public static short e_ip(Address s) { return s.add(e_ip).getShort(); }
        public static void e_ip(Address s, short v) { s.add(e_ip).putShort(v); }
        public static short e_cs(Address s) { return s.add(e_cs).getShort(); }
        public static void e_cs(Address s, short v) { s.add(e_cs).putShort(v); }
        public static short e_lfarlc(Address s) { return s.add(e_lfarlc).getShort(); }
        public static void e_lfarlc(Address s, short v) { s.add(e_lfarlc).putShort(v); }
        public static short e_ovno(Address s) { return s.add(e_ovno).getShort(); }
        public static void e_ovno(Address s, short v) { s.add(e_ovno).putShort(v); }
        public static short e_oemid(Address s) { return s.add(e_oemid).getShort(); }
        public static void e_oemid(Address s, short v) { s.add(e_oemid).putShort(v); }
        public static short e_oeminfo(Address s) { return s.add(e_oeminfo).getShort(); }
        public static void e_oeminfo(Address s, short v) { s.add(e_oeminfo).putShort(v); }
        public static int e_lfanew(Address s) { return s.add(e_lfanew).getInt(); }
        public static void e_lfanew(Address s, int v) { s.add(e_lfanew).putInt(v); }
    }

    /** {@code struct _IMAGE_FILE_HEADER} - winnt.h:7547, 20 bytes */
    public static final class IMAGE_FILE_HEADER {
        private IMAGE_FILE_HEADER() {}
        public static final int SIZE = 20;
        /** {@code WORD Machine} */ public static final int Machine = 0;
        /** {@code WORD NumberOfSections} */ public static final int NumberOfSections = 2;
        /** {@code DWORD TimeDateStamp} */ public static final int TimeDateStamp = 4;
        /** {@code DWORD PointerToSymbolTable} */ public static final int PointerToSymbolTable = 8;
        /** {@code DWORD NumberOfSymbols} */ public static final int NumberOfSymbols = 12;
        /** {@code WORD SizeOfOptionalHeader} */ public static final int SizeOfOptionalHeader = 16;
        /** {@code WORD Characteristics} */ public static final int Characteristics = 18;
        public static short Machine(Address s) { return s.add(Machine).getShort(); }
        public static void Machine(Address s, short v) { s.add(Machine).putShort(v); }
        public static short NumberOfSections(Address s) { return s.add(NumberOfSections).getShort(); }
        public static void NumberOfSections(Address s, short v) { s.add(NumberOfSections).putShort(v); }
        public static int TimeDateStamp(Address s) { return s.add(TimeDateStamp).getInt(); }
        public static void TimeDateStamp(Address s, int v) { s.add(TimeDateStamp).putInt(v); }
        public static int PointerToSymbolTable(Address s) { return s.add(PointerToSymbolTable).getInt(); }
        public static void PointerToSymbolTable(Address s, int v) { s.add(PointerToSymbolTable).putInt(v); }
        public static int NumberOfSymbols(Address s) { return s.add(NumberOfSymbols).getInt(); }
        public static void NumberOfSymbols(Address s, int v) { s.add(NumberOfSymbols).putInt(v); }
        public static short SizeOfOptionalHeader(Address s) { return s.add(SizeOfOptionalHeader).getShort(); }
        public static void SizeOfOptionalHeader(Address s, short v) { s.add(SizeOfOptionalHeader).putShort(v); }
        public static short Characteristics(Address s) { return s.add(Characteristics).getShort(); }
        public static void Characteristics(Address s, short v) { s.add(Characteristics).putShort(v); }
    }

    /** {@code struct _IMAGE_OPTIONAL_HEADER} - winnt.h:7615, 224 bytes */
    public static final class IMAGE_OPTIONAL_HEADER32 {
        private IMAGE_OPTIONAL_HEADER32() {}
        public static final int SIZE = 224;
        /** {@code WORD Magic} */ public static final int Magic = 0;
        /** {@code BYTE MajorLinkerVersion} */ public static final int MajorLinkerVersion = 2;
        /** {@code BYTE MinorLinkerVersion} */ public static final int MinorLinkerVersion = 3;
        /** {@code DWORD SizeOfCode} */ public static final int SizeOfCode = 4;
        /** {@code DWORD SizeOfInitializedData} */ public static final int SizeOfInitializedData = 8;
        /** {@code DWORD SizeOfUninitializedData} */ public static final int SizeOfUninitializedData = 12;
        /** {@code DWORD AddressOfEntryPoint} */ public static final int AddressOfEntryPoint = 16;
        /** {@code DWORD BaseOfCode} */ public static final int BaseOfCode = 20;
        /** {@code DWORD BaseOfData} */ public static final int BaseOfData = 24;
        /** {@code DWORD ImageBase} */ public static final int ImageBase = 28;
        /** {@code DWORD SectionAlignment} */ public static final int SectionAlignment = 32;
        /** {@code DWORD FileAlignment} */ public static final int FileAlignment = 36;
        /** {@code WORD MajorOperatingSystemVersion} */ public static final int MajorOperatingSystemVersion = 40;
        /** {@code WORD MinorOperatingSystemVersion} */ public static final int MinorOperatingSystemVersion = 42;
        /** {@code WORD MajorImageVersion} */ public static final int MajorImageVersion = 44;
        /** {@code WORD MinorImageVersion} */ public static final int MinorImageVersion = 46;
        /** {@code WORD MajorSubsystemVersion} */ public static final int MajorSubsystemVersion = 48;
        /** {@code WORD MinorSubsystemVersion} */ public static final int MinorSubsystemVersion = 50;
        /** {@code DWORD Win32VersionValue} */ public static final int Win32VersionValue = 52;
        /** {@code DWORD SizeOfImage} */ public static final int SizeOfImage = 56;
        /** {@code DWORD SizeOfHeaders} */ public static final int SizeOfHeaders = 60;
        /** {@code DWORD CheckSum} */ public static final int CheckSum = 64;
        /** {@code WORD Subsystem} */ public static final int Subsystem = 68;
        /** {@code WORD DllCharacteristics} */ public static final int DllCharacteristics = 70;
        /** {@code DWORD SizeOfStackReserve} */ public static final int SizeOfStackReserve = 72;
        /** {@code DWORD SizeOfStackCommit} */ public static final int SizeOfStackCommit = 76;
        /** {@code DWORD SizeOfHeapReserve} */ public static final int SizeOfHeapReserve = 80;
        /** {@code DWORD SizeOfHeapCommit} */ public static final int SizeOfHeapCommit = 84;
        /** {@code DWORD LoaderFlags} */ public static final int LoaderFlags = 88;
        /** {@code DWORD NumberOfRvaAndSizes} */ public static final int NumberOfRvaAndSizes = 92;
        /** {@code IMAGE_DATA_DIRECTORY[16] DataDirectory} */ public static final int DataDirectory = 96;
        public static short Magic(Address s) { return s.add(Magic).getShort(); }
        public static void Magic(Address s, short v) { s.add(Magic).putShort(v); }
        public static byte MajorLinkerVersion(Address s) { return s.add(MajorLinkerVersion).getByte(); }
        public static void MajorLinkerVersion(Address s, byte v) { s.add(MajorLinkerVersion).putByte(v); }
        public static byte MinorLinkerVersion(Address s) { return s.add(MinorLinkerVersion).getByte(); }
        public static void MinorLinkerVersion(Address s, byte v) { s.add(MinorLinkerVersion).putByte(v); }
        public static int SizeOfCode(Address s) { return s.add(SizeOfCode).getInt(); }
        public static void SizeOfCode(Address s, int v) { s.add(SizeOfCode).putInt(v); }
        public static int SizeOfInitializedData(Address s) { return s.add(SizeOfInitializedData).getInt(); }
        public static void SizeOfInitializedData(Address s, int v) { s.add(SizeOfInitializedData).putInt(v); }
        public static int SizeOfUninitializedData(Address s) { return s.add(SizeOfUninitializedData).getInt(); }
        public static void SizeOfUninitializedData(Address s, int v) { s.add(SizeOfUninitializedData).putInt(v); }
        public static int AddressOfEntryPoint(Address s) { return s.add(AddressOfEntryPoint).getInt(); }
        public static void AddressOfEntryPoint(Address s, int v) { s.add(AddressOfEntryPoint).putInt(v); }
        public static int BaseOfCode(Address s) { return s.add(BaseOfCode).getInt(); }
        public static void BaseOfCode(Address s, int v) { s.add(BaseOfCode).putInt(v); }
        public static int BaseOfData(Address s) { return s.add(BaseOfData).getInt(); }
        public static void BaseOfData(Address s, int v) { s.add(BaseOfData).putInt(v); }
        public static int ImageBase(Address s) { return s.add(ImageBase).getInt(); }
        public static void ImageBase(Address s, int v) { s.add(ImageBase).putInt(v); }
        public static int SectionAlignment(Address s) { return s.add(SectionAlignment).getInt(); }
        public static void SectionAlignment(Address s, int v) { s.add(SectionAlignment).putInt(v); }
        public static int FileAlignment(Address s) { return s.add(FileAlignment).getInt(); }
        public static void FileAlignment(Address s, int v) { s.add(FileAlignment).putInt(v); }
        public static short MajorOperatingSystemVersion(Address s) { return s.add(MajorOperatingSystemVersion).getShort(); }
        public static void MajorOperatingSystemVersion(Address s, short v) { s.add(MajorOperatingSystemVersion).putShort(v); }
        public static short MinorOperatingSystemVersion(Address s) { return s.add(MinorOperatingSystemVersion).getShort(); }
        public static void MinorOperatingSystemVersion(Address s, short v) { s.add(MinorOperatingSystemVersion).putShort(v); }
        public static short MajorImageVersion(Address s) { return s.add(MajorImageVersion).getShort(); }
        public static void MajorImageVersion(Address s, short v) { s.add(MajorImageVersion).putShort(v); }
        public static short MinorImageVersion(Address s) { return s.add(MinorImageVersion).getShort(); }
        public static void MinorImageVersion(Address s, short v) { s.add(MinorImageVersion).putShort(v); }
        public static short MajorSubsystemVersion(Address s) { return s.add(MajorSubsystemVersion).getShort(); }
        public static void MajorSubsystemVersion(Address s, short v) { s.add(MajorSubsystemVersion).putShort(v); }
        public static short MinorSubsystemVersion(Address s) { return s.add(MinorSubsystemVersion).getShort(); }
        public static void MinorSubsystemVersion(Address s, short v) { s.add(MinorSubsystemVersion).putShort(v); }
        public static int Win32VersionValue(Address s) { return s.add(Win32VersionValue).getInt(); }
        public static void Win32VersionValue(Address s, int v) { s.add(Win32VersionValue).putInt(v); }
        public static int SizeOfImage(Address s) { return s.add(SizeOfImage).getInt(); }
        public static void SizeOfImage(Address s, int v) { s.add(SizeOfImage).putInt(v); }
        public static int SizeOfHeaders(Address s) { return s.add(SizeOfHeaders).getInt(); }
        public static void SizeOfHeaders(Address s, int v) { s.add(SizeOfHeaders).putInt(v); }
        public static int CheckSum(Address s) { return s.add(CheckSum).getInt(); }
        public static void CheckSum(Address s, int v) { s.add(CheckSum).putInt(v); }
        public static short Subsystem(Address s) { return s.add(Subsystem).getShort(); }
        public static void Subsystem(Address s, short v) { s.add(Subsystem).putShort(v); }
        public static short DllCharacteristics(Address s) { return s.add(DllCharacteristics).getShort(); }
        public static void DllCharacteristics(Address s, short v) { s.add(DllCharacteristics).putShort(v); }
        public static int SizeOfStackReserve(Address s) { return s.add(SizeOfStackReserve).getInt(); }
        public static void SizeOfStackReserve(Address s, int v) { s.add(SizeOfStackReserve).putInt(v); }
        public static int SizeOfStackCommit(Address s) { return s.add(SizeOfStackCommit).getInt(); }
        public static void SizeOfStackCommit(Address s, int v) { s.add(SizeOfStackCommit).putInt(v); }
        public static int SizeOfHeapReserve(Address s) { return s.add(SizeOfHeapReserve).getInt(); }
        public static void SizeOfHeapReserve(Address s, int v) { s.add(SizeOfHeapReserve).putInt(v); }
        public static int SizeOfHeapCommit(Address s) { return s.add(SizeOfHeapCommit).getInt(); }
        public static void SizeOfHeapCommit(Address s, int v) { s.add(SizeOfHeapCommit).putInt(v); }
        public static int LoaderFlags(Address s) { return s.add(LoaderFlags).getInt(); }
        public static void LoaderFlags(Address s, int v) { s.add(LoaderFlags).putInt(v); }
        public static int NumberOfRvaAndSizes(Address s) { return s.add(NumberOfRvaAndSizes).getInt(); }
        public static void NumberOfRvaAndSizes(Address s, int v) { s.add(NumberOfRvaAndSizes).putInt(v); }
    }

    /** {@code struct _IMAGE_OPTIONAL_HEADER64} - winnt.h:7666, 240 bytes */
    public static final class IMAGE_OPTIONAL_HEADER64 {
        private IMAGE_OPTIONAL_HEADER64() {}
        public static final int SIZE = 240;
        /** {@code WORD Magic} */ public static final int Magic = 0;
        /** {@code BYTE MajorLinkerVersion} */ public static final int MajorLinkerVersion = 2;
        /** {@code BYTE MinorLinkerVersion} */ public static final int MinorLinkerVersion = 3;
        /** {@code DWORD SizeOfCode} */ public static final int SizeOfCode = 4;
        /** {@code DWORD SizeOfInitializedData} */ public static final int SizeOfInitializedData = 8;
        /** {@code DWORD SizeOfUninitializedData} */ public static final int SizeOfUninitializedData = 12;
        /** {@code DWORD AddressOfEntryPoint} */ public static final int AddressOfEntryPoint = 16;
        /** {@code DWORD BaseOfCode} */ public static final int BaseOfCode = 20;
        /** {@code ULONGLONG ImageBase} */ public static final int ImageBase = 24;
        /** {@code DWORD SectionAlignment} */ public static final int SectionAlignment = 32;
        /** {@code DWORD FileAlignment} */ public static final int FileAlignment = 36;
        /** {@code WORD MajorOperatingSystemVersion} */ public static final int MajorOperatingSystemVersion = 40;
        /** {@code WORD MinorOperatingSystemVersion} */ public static final int MinorOperatingSystemVersion = 42;
        /** {@code WORD MajorImageVersion} */ public static final int MajorImageVersion = 44;
        /** {@code WORD MinorImageVersion} */ public static final int MinorImageVersion = 46;
        /** {@code WORD MajorSubsystemVersion} */ public static final int MajorSubsystemVersion = 48;
        /** {@code WORD MinorSubsystemVersion} */ public static final int MinorSubsystemVersion = 50;
        /** {@code DWORD Win32VersionValue} */ public static final int Win32VersionValue = 52;
        /** {@code DWORD SizeOfImage} */ public static final int SizeOfImage = 56;
        /** {@code DWORD SizeOfHeaders} */ public static final int SizeOfHeaders = 60;
        /** {@code DWORD CheckSum} */ public static final int CheckSum = 64;
        /** {@code WORD Subsystem} */ public static final int Subsystem = 68;
        /** {@code WORD DllCharacteristics} */ public static final int DllCharacteristics = 70;
        /** {@code ULONGLONG SizeOfStackReserve} */ public static final int SizeOfStackReserve = 72;
        /** {@code ULONGLONG SizeOfStackCommit} */ public static final int SizeOfStackCommit = 80;
        /** {@code ULONGLONG SizeOfHeapReserve} */ public static final int SizeOfHeapReserve = 88;
        /** {@code ULONGLONG SizeOfHeapCommit} */ public static final int SizeOfHeapCommit = 96;
        /** {@code DWORD LoaderFlags} */ public static final int LoaderFlags = 104;
        /** {@code DWORD NumberOfRvaAndSizes} */ public static final int NumberOfRvaAndSizes = 108;
        /** {@code IMAGE_DATA_DIRECTORY[16] DataDirectory} */ public static final int DataDirectory = 112;
        public static short Magic(Address s) { return s.add(Magic).getShort(); }
        public static void Magic(Address s, short v) { s.add(Magic).putShort(v); }
        public static byte MajorLinkerVersion(Address s) { return s.add(MajorLinkerVersion).getByte(); }
        public static void MajorLinkerVersion(Address s, byte v) { s.add(MajorLinkerVersion).putByte(v); }
        public static byte MinorLinkerVersion(Address s) { return s.add(MinorLinkerVersion).getByte(); }
        public static void MinorLinkerVersion(Address s, byte v) { s.add(MinorLinkerVersion).putByte(v); }
        public static int SizeOfCode(Address s) { return s.add(SizeOfCode).getInt(); }
        public static void SizeOfCode(Address s, int v) { s.add(SizeOfCode).putInt(v); }
        public static int SizeOfInitializedData(Address s) { return s.add(SizeOfInitializedData).getInt(); }
        public static void SizeOfInitializedData(Address s, int v) { s.add(SizeOfInitializedData).putInt(v); }
        public static int SizeOfUninitializedData(Address s) { return s.add(SizeOfUninitializedData).getInt(); }
        public static void SizeOfUninitializedData(Address s, int v) { s.add(SizeOfUninitializedData).putInt(v); }
        public static int AddressOfEntryPoint(Address s) { return s.add(AddressOfEntryPoint).getInt(); }
        public static void AddressOfEntryPoint(Address s, int v) { s.add(AddressOfEntryPoint).putInt(v); }
        public static int BaseOfCode(Address s) { return s.add(BaseOfCode).getInt(); }
        public static void BaseOfCode(Address s, int v) { s.add(BaseOfCode).putInt(v); }
        public static long ImageBase(Address s) { return s.add(ImageBase).getLong(); }
        public static void ImageBase(Address s, long v) { s.add(ImageBase).putLong(v); }
        public static int SectionAlignment(Address s) { return s.add(SectionAlignment).getInt(); }
        public static void SectionAlignment(Address s, int v) { s.add(SectionAlignment).putInt(v); }
        public static int FileAlignment(Address s) { return s.add(FileAlignment).getInt(); }
        public static void FileAlignment(Address s, int v) { s.add(FileAlignment).putInt(v); }
        public static short MajorOperatingSystemVersion(Address s) { return s.add(MajorOperatingSystemVersion).getShort(); }
        public static void MajorOperatingSystemVersion(Address s, short v) { s.add(MajorOperatingSystemVersion).putShort(v); }
        public static short MinorOperatingSystemVersion(Address s) { return s.add(MinorOperatingSystemVersion).getShort(); }
        public static void MinorOperatingSystemVersion(Address s, short v) { s.add(MinorOperatingSystemVersion).putShort(v); }
        public static short MajorImageVersion(Address s) { return s.add(MajorImageVersion).getShort(); }
        public static void MajorImageVersion(Address s, short v) { s.add(MajorImageVersion).putShort(v); }
        public static short MinorImageVersion(Address s) { return s.add(MinorImageVersion).getShort(); }
        public static void MinorImageVersion(Address s, short v) { s.add(MinorImageVersion).putShort(v); }
        public static short MajorSubsystemVersion(Address s) { return s.add(MajorSubsystemVersion).getShort(); }
        public static void MajorSubsystemVersion(Address s, short v) { s.add(MajorSubsystemVersion).putShort(v); }
        public static short MinorSubsystemVersion(Address s) { return s.add(MinorSubsystemVersion).getShort(); }
        public static void MinorSubsystemVersion(Address s, short v) { s.add(MinorSubsystemVersion).putShort(v); }
        public static int Win32VersionValue(Address s) { return s.add(Win32VersionValue).getInt(); }
        public static void Win32VersionValue(Address s, int v) { s.add(Win32VersionValue).putInt(v); }
        public static int SizeOfImage(Address s) { return s.add(SizeOfImage).getInt(); }
        public static void SizeOfImage(Address s, int v) { s.add(SizeOfImage).putInt(v); }
        public static int SizeOfHeaders(Address s) { return s.add(SizeOfHeaders).getInt(); }
        public static void SizeOfHeaders(Address s, int v) { s.add(SizeOfHeaders).putInt(v); }
        public static int CheckSum(Address s) { return s.add(CheckSum).getInt(); }
        public static void CheckSum(Address s, int v) { s.add(CheckSum).putInt(v); }
        public static short Subsystem(Address s) { return s.add(Subsystem).getShort(); }
        public static void Subsystem(Address s, short v) { s.add(Subsystem).putShort(v); }
        public static short DllCharacteristics(Address s) { return s.add(DllCharacteristics).getShort(); }
        public static void DllCharacteristics(Address s, short v) { s.add(DllCharacteristics).putShort(v); }
        public static long SizeOfStackReserve(Address s) { return s.add(SizeOfStackReserve).getLong(); }
        public static void SizeOfStackReserve(Address s, long v) { s.add(SizeOfStackReserve).putLong(v); }
        public static long SizeOfStackCommit(Address s) { return s.add(SizeOfStackCommit).getLong(); }
        public static void SizeOfStackCommit(Address s, long v) { s.add(SizeOfStackCommit).putLong(v); }
        public static long SizeOfHeapReserve(Address s) { return s.add(SizeOfHeapReserve).getLong(); }
        public static void SizeOfHeapReserve(Address s, long v) { s.add(SizeOfHeapReserve).putLong(v); }
        public static long SizeOfHeapCommit(Address s) { return s.add(SizeOfHeapCommit).getLong(); }
        public static void SizeOfHeapCommit(Address s, long v) { s.add(SizeOfHeapCommit).putLong(v); }
        public static int LoaderFlags(Address s) { return s.add(LoaderFlags).getInt(); }
        public static void LoaderFlags(Address s, int v) { s.add(LoaderFlags).putInt(v); }
        public static int NumberOfRvaAndSizes(Address s) { return s.add(NumberOfRvaAndSizes).getInt(); }
        public static void NumberOfRvaAndSizes(Address s, int v) { s.add(NumberOfRvaAndSizes).putInt(v); }
    }

    /** {@code struct _IMAGE_DATA_DIRECTORY} - winnt.h:7608, 8 bytes */
    public static final class IMAGE_DATA_DIRECTORY {
        private IMAGE_DATA_DIRECTORY() {}
        public static final int SIZE = 8;
        /** {@code DWORD VirtualAddress} */ public static final int VirtualAddress = 0;
        /** {@code DWORD Size} */ public static final int Size = 4;
        public static int VirtualAddress(Address s) { return s.add(VirtualAddress).getInt(); }
        public static void VirtualAddress(Address s, int v) { s.add(VirtualAddress).putInt(v); }
        public static int Size(Address s) { return s.add(Size).getInt(); }
        public static void Size(Address s, int v) { s.add(Size).putInt(v); }
    }

    /** {@code struct _CRYPTOAPI_BLOB} - wincrypt.h:769, 16 bytes */
    public static final class CRYPT_DATA_BLOB {
        private CRYPT_DATA_BLOB() {}
        public static final int SIZE = 16;
        /** {@code DWORD cbData} */ public static final int cbData = 0;
        /** {@code BYTE* pbData} */ public static final int pbData = 8;
        public static int cbData(Address s) { return s.add(cbData).getInt(); }
        public static void cbData(Address s, int v) { s.add(cbData).putInt(v); }
        public static Address pbData(Address s) { return s.add(pbData).getAddress(); }
        public static void pbData(Address s, Address v) { s.add(pbData).putAddress(v); }
    }

    /** {@code struct } - mssign.h:13, 24 bytes */
    public static final class SIGNER_FILE_INFO {
        private SIGNER_FILE_INFO() {}
        public static final int SIZE = 24;
        /** {@code DWORD cbSize} */ public static final int cbSize = 0;
        /** {@code LPCWSTR pwszFileName} */ public static final int pwszFileName = 8;
        /** {@code HANDLE hFile} */ public static final int hFile = 16;
        public static int cbSize(Address s) { return s.add(cbSize).getInt(); }
        public static void cbSize(Address s, int v) { s.add(cbSize).putInt(v); }
        public static Address pwszFileName(Address s) { return s.add(pwszFileName).getAddress(); }
        public static void pwszFileName(Address s, Address v) { s.add(pwszFileName).putAddress(v); }
        public static Address hFile(Address s) { return s.add(hFile).getAddress(); }
        public static void hFile(Address s, Address v) { s.add(hFile).putAddress(v); }
    }

    /** {@code struct } - mssign.h:19, 32 bytes */
    public static final class SIGNER_SUBJECT_INFO {
        private SIGNER_SUBJECT_INFO() {}
        public static final int SIZE = 32;
        /** {@code DWORD cbSize} */ public static final int cbSize = 0;
        /** {@code DWORD* pdwIndex} */ public static final int pdwIndex = 8;
        /** {@code DWORD dwSubjectChoice} */ public static final int dwSubjectChoice = 16;
        /** {@code SIGNER_FILE_INFO* pSignerFileInfo} */ public static final int pSignerFileInfo = 24;
        public static int cbSize(Address s) { return s.add(cbSize).getInt(); }
        public static void cbSize(Address s, int v) { s.add(cbSize).putInt(v); }
        public static Address pdwIndex(Address s) { return s.add(pdwIndex).getAddress(); }
        public static void pdwIndex(Address s, Address v) { s.add(pdwIndex).putAddress(v); }
        public static int dwSubjectChoice(Address s) { return s.add(dwSubjectChoice).getInt(); }
        public static void dwSubjectChoice(Address s, int v) { s.add(dwSubjectChoice).putInt(v); }
        public static Address pSignerFileInfo(Address s) { return s.add(pSignerFileInfo).getAddress(); }
        public static void pSignerFileInfo(Address s, Address v) { s.add(pSignerFileInfo).putAddress(v); }
    }

    /** {@code struct } - mssign.h:26, 32 bytes */
    public static final class SIGNER_CERT_STORE_INFO {
        private SIGNER_CERT_STORE_INFO() {}
        public static final int SIZE = 32;
        /** {@code DWORD cbSize} */ public static final int cbSize = 0;
        /** {@code PCCERT_CONTEXT pSigningCert} */ public static final int pSigningCert = 8;
        /** {@code DWORD dwCertPolicy} */ public static final int dwCertPolicy = 16;
        /** {@code HCERTSTORE hCertStore} */ public static final int hCertStore = 24;
        public static int cbSize(Address s) { return s.add(cbSize).getInt(); }
        public static void cbSize(Address s, int v) { s.add(cbSize).putInt(v); }
        public static Address pSigningCert(Address s) { return s.add(pSigningCert).getAddress(); }
        public static void pSigningCert(Address s, Address v) { s.add(pSigningCert).putAddress(v); }
        public static int dwCertPolicy(Address s) { return s.add(dwCertPolicy).getInt(); }
        public static void dwCertPolicy(Address s, int v) { s.add(dwCertPolicy).putInt(v); }
        public static Address hCertStore(Address s) { return s.add(hCertStore).getAddress(); }
        public static void hCertStore(Address s, Address v) { s.add(hCertStore).putAddress(v); }
    }

    /** {@code struct } - mssign.h:33, 24 bytes */
    public static final class SIGNER_CERT {
        private SIGNER_CERT() {}
        public static final int SIZE = 24;
        /** {@code DWORD cbSize} */ public static final int cbSize = 0;
        /** {@code DWORD dwCertChoice} */ public static final int dwCertChoice = 4;
        /** {@code SIGNER_CERT_STORE_INFO* pCertStoreInfo} */ public static final int pCertStoreInfo = 8;
        /** {@code HWND hwnd} */ public static final int hwnd = 16;
        public static int cbSize(Address s) { return s.add(cbSize).getInt(); }
        public static void cbSize(Address s, int v) { s.add(cbSize).putInt(v); }
        public static int dwCertChoice(Address s) { return s.add(dwCertChoice).getInt(); }
        public static void dwCertChoice(Address s, int v) { s.add(dwCertChoice).putInt(v); }
        public static Address pCertStoreInfo(Address s) { return s.add(pCertStoreInfo).getAddress(); }
        public static void pCertStoreInfo(Address s, Address v) { s.add(pCertStoreInfo).putAddress(v); }
        public static Address hwnd(Address s) { return s.add(hwnd).getAddress(); }
        public static void hwnd(Address s, Address v) { s.add(hwnd).putAddress(v); }
    }

    /** {@code struct } - mssign.h:40, 40 bytes */
    public static final class SIGNER_SIGNATURE_INFO {
        private SIGNER_SIGNATURE_INFO() {}
        public static final int SIZE = 40;
        /** {@code DWORD cbSize} */ public static final int cbSize = 0;
        /** {@code ALG_ID algidHash} */ public static final int algidHash = 4;
        /** {@code DWORD dwAttrChoice} */ public static final int dwAttrChoice = 8;
        /** {@code void* pAttrAuthcode} */ public static final int pAttrAuthcode = 16;
        /** {@code PCRYPT_ATTRIBUTES psAuthenticated} */ public static final int psAuthenticated = 24;
        /** {@code PCRYPT_ATTRIBUTES psUnauthenticated} */ public static final int psUnauthenticated = 32;
        public static int cbSize(Address s) { return s.add(cbSize).getInt(); }
        public static void cbSize(Address s, int v) { s.add(cbSize).putInt(v); }
        public static int algidHash(Address s) { return s.add(algidHash).getInt(); }
        public static void algidHash(Address s, int v) { s.add(algidHash).putInt(v); }
        public static int dwAttrChoice(Address s) { return s.add(dwAttrChoice).getInt(); }
        public static void dwAttrChoice(Address s, int v) { s.add(dwAttrChoice).putInt(v); }
        public static Address pAttrAuthcode(Address s) { return s.add(pAttrAuthcode).getAddress(); }
        public static void pAttrAuthcode(Address s, Address v) { s.add(pAttrAuthcode).putAddress(v); }
        public static Address psAuthenticated(Address s) { return s.add(psAuthenticated).getAddress(); }
        public static void psAuthenticated(Address s, Address v) { s.add(psAuthenticated).putAddress(v); }
        public static Address psUnauthenticated(Address s) { return s.add(psUnauthenticated).getAddress(); }
        public static void psUnauthenticated(Address s, Address v) { s.add(psUnauthenticated).putAddress(v); }
    }

    /** {@code struct } - mssign.h:49, 16 bytes */
    public static final class SIGNER_CONTEXT {
        private SIGNER_CONTEXT() {}
        public static final int SIZE = 16;
        /** {@code DWORD cbSize} */ public static final int cbSize = 0;
        /** {@code DWORD cbBlob} */ public static final int cbBlob = 4;
        /** {@code BYTE* pbBlob} */ public static final int pbBlob = 8;
        public static int cbSize(Address s) { return s.add(cbSize).getInt(); }
        public static void cbSize(Address s, int v) { s.add(cbSize).putInt(v); }
        public static int cbBlob(Address s) { return s.add(cbBlob).getInt(); }
        public static void cbBlob(Address s, int v) { s.add(cbBlob).putInt(v); }
        public static Address pbBlob(Address s) { return s.add(pbBlob).getAddress(); }
        public static void pbBlob(Address s, Address v) { s.add(pbBlob).putAddress(v); }
    }

}
