package jarrunner.jr;

import org.teavm.interop.Address;
import org.teavm.interop.Import;

/** GENERATED by jextract-teavm - do not hand-edit.
 *  from jr.h, target x86_64-w64-mingw32 (LLP64). Symbols: winapi.symbols */
@SuppressWarnings("unused")
public final class WinApi {
    private WinApi() {}

    /** {@code void exit(int _Code)} - stdlib.h:242 */
    @Import(name = "exit") public static native void exit(int _Code);

    /** {@code char *getenv(const char *_VarName)} - stdlib.h:296 */
    @Import(name = "getenv") public static native Address getenv(Address _VarName);

    /** {@code FILE *fopen(const char *restrict _Filename, const char *restrict _Mode)} - stdio.h:521 */
    @Import(name = "fopen") public static native Address fopen(Address _Filename, Address _Mode);

    /** {@code int fputs(const char *restrict _Str, FILE *restrict _File)} - stdio.h:525 */
    @Import(name = "fputs") public static native int fputs(Address _Str, Address _File);

    /** {@code int fflush(FILE *_File)} - stdio.h:502 */
    @Import(name = "fflush") public static native int fflush(Address _File);

    /** {@code int fclose(FILE *_File)} - stdio.h:493 */
    @Import(name = "fclose") public static native int fclose(Address _File);

    /** {@code unsigned long long fread(void *restrict _DstBuf, size_t _ElementSize, size_t _Count, FILE *restrict _File)} - stdio.h:526 */
    @Import(name = "fread") public static native long fread(Address _DstBuf, long _ElementSize, long _Count, Address _File);

    /** {@code unsigned long long fwrite(const void *restrict _Str, size_t _Size, size_t _Count, FILE *restrict _File)} - stdio.h:549 */
    @Import(name = "fwrite") public static native long fwrite(Address _Str, long _Size, long _Count, Address _File);

    /** {@code void *malloc(size_t _Size)} - corecrt_malloc.h:44 */
    @Import(name = "malloc") public static native Address malloc(long _Size);

    /** {@code void free(void *_Memory)} - corecrt_malloc.h:43 */
    @Import(name = "free") public static native void free(Address _Memory);

    /** {@code void *memset(void *_Dst, int _Val, size_t _Size)} - corecrt_memory.h:23 */
    @Import(name = "memset") public static native Address memset(Address _Dst, int _Val, long _Size);

    /** {@code time_t time(time_t *_Time)} - time.h:128 */
    @Import(name = "time") public static native long time(Address _Time);

    /** {@code WINBOOL QueryPerformanceCounter(LARGE_INTEGER *lpPerformanceCount)} - profileapi.h:16 */
    @Import(name = "QueryPerformanceCounter") public static native int queryPerformanceCounter(Address lpPerformanceCount);

    /** {@code WINBOOL QueryPerformanceFrequency(LARGE_INTEGER *lpFrequency)} - profileapi.h:17 */
    @Import(name = "QueryPerformanceFrequency") public static native int queryPerformanceFrequency(Address lpFrequency);

    /** {@code HWND GetConsoleWindow()} - consoleapi3.h:88 */
    @Import(name = "GetConsoleWindow") public static native Address getConsoleWindow();

    /** {@code WINBOOL ShowWindow(HWND hWnd, int nCmdShow)} - winuser.h:2213 */
    @Import(name = "ShowWindow") public static native int showWindow(Address hWnd, int nCmdShow);

    /** {@code WINBOOL FreeConsole()} - consoleapi.h:51 */
    @Import(name = "FreeConsole") public static native int freeConsole();

    /** {@code WINBOOL AttachConsole(DWORD process_id)} - consoleapi.h:55 */
    @Import(name = "AttachConsole") public static native int attachConsole(int process_id);

    /** {@code HANDLE GetStdHandle(DWORD nStdHandle)} - processenv.h:57 */
    @Import(name = "GetStdHandle") public static native Address getStdHandle(int nStdHandle);

    /** {@code WINBOOL SetStdHandle(DWORD nStdHandle, HANDLE hHandle)} - processenv.h:66 */
    @Import(name = "SetStdHandle") public static native int setStdHandle(int nStdHandle, Address hHandle);

    /** {@code WINBOOL GetConsoleMode(HANDLE console_handle, LPDWORD mode)} - consoleapi.h:81 */
    @Import(name = "GetConsoleMode") public static native int getConsoleMode(Address console_handle, Address mode);

    /** {@code HANDLE CreateFileA(LPCSTR lpFileName, DWORD dwDesiredAccess, DWORD dwShareMode, LPSECURITY_ATTRIBUTES lpSecurityAttributes, DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes, HANDLE hTemplateFile)} - fileapi.h:53 */
    @Import(name = "CreateFileA") public static native Address createFileA(Address lpFileName, int dwDesiredAccess, int dwShareMode, Address lpSecurityAttributes, int dwCreationDisposition, int dwFlagsAndAttributes, Address hTemplateFile);

    /** {@code DWORD GetFileAttributesA(LPCSTR lpFileName)} - fileapi.h:77 */
    @Import(name = "GetFileAttributesA") public static native int getFileAttributesA(Address lpFileName);

    /** {@code WINBOOL GetFileAttributesExA(LPCSTR lpFileName, GET_FILEEX_INFO_LEVELS fInfoLevelId, LPVOID lpFileInformation)} - fileapi.h:203 */
    @Import(name = "GetFileAttributesExA") public static native int getFileAttributesExA(Address lpFileName, int fInfoLevelId, Address lpFileInformation);

    /** {@code HANDLE FindFirstFileA(LPCSTR lpFileName, LPWIN32_FIND_DATAA lpFindFileData)} - fileapi.h:71 */
    @Import(name = "FindFirstFileA") public static native Address findFirstFileA(Address lpFileName, Address lpFindFileData);

    /** {@code WINBOOL FindNextFileA(HANDLE hFindFile, LPWIN32_FIND_DATAA lpFindFileData)} - fileapi.h:198 */
    @Import(name = "FindNextFileA") public static native int findNextFileA(Address hFindFile, Address lpFindFileData);

    /** {@code WINBOOL FindClose(HANDLE hFindFile)} - fileapi.h:195 */
    @Import(name = "FindClose") public static native int findClose(Address hFindFile);

    /** {@code WINBOOL DeleteFileA(LPCSTR lpFileName)} - fileapi.h:193 */
    @Import(name = "DeleteFileA") public static native int deleteFileA(Address lpFileName);

    /** {@code DWORD GetModuleFileNameA(HMODULE hModule, LPSTR lpFilename, DWORD nSize)} - libloaderapi.h:113 */
    @Import(name = "GetModuleFileNameA") public static native int getModuleFileNameA(Address hModule, Address lpFilename, int nSize);

    /** {@code DWORD GetCurrentDirectoryA(DWORD nBufferLength, LPSTR lpBuffer)} - processenv.h:22 */
    @Import(name = "GetCurrentDirectoryA") public static native int getCurrentDirectoryA(int nBufferLength, Address lpBuffer);

    /** {@code WINBOOL SetEnvironmentVariableA(LPCSTR lpName, LPCSTR lpValue)} - processenv.h:64 */
    @Import(name = "SetEnvironmentVariableA") public static native int setEnvironmentVariableA(Address lpName, Address lpValue);

    /** {@code int MessageBoxA(HWND hWnd, LPCSTR lpText, LPCSTR lpCaption, UINT uType)} - winuser.h:3716 */
    @Import(name = "MessageBoxA") public static native int messageBoxA(Address hWnd, Address lpText, Address lpCaption, int uType);

    /** {@code WINBOOL OpenClipboard(HWND hWndNewOwner)} - winuser.h:2479 */
    @Import(name = "OpenClipboard") public static native int openClipboard(Address hWndNewOwner);

    /** {@code WINBOOL EmptyClipboard()} - winuser.h:2494 */
    @Import(name = "EmptyClipboard") public static native int emptyClipboard();

    /** {@code HANDLE SetClipboardData(UINT uFormat, HANDLE hMem)} - winuser.h:2486 */
    @Import(name = "SetClipboardData") public static native Address setClipboardData(int uFormat, Address hMem);

    /** {@code WINBOOL CloseClipboard()} - winuser.h:2480 */
    @Import(name = "CloseClipboard") public static native int closeClipboard();

    /** {@code HGLOBAL GlobalAlloc(UINT uFlags, SIZE_T dwBytes)} - winbase.h:1201 */
    @Import(name = "GlobalAlloc") public static native Address globalAlloc(int uFlags, long dwBytes);

    /** {@code LPVOID GlobalLock(HGLOBAL hMem)} - winbase.h:1204 */
    @Import(name = "GlobalLock") public static native Address globalLock(Address hMem);

    /** {@code WINBOOL GlobalUnlock(HGLOBAL hMem)} - winbase.h:1205 */
    @Import(name = "GlobalUnlock") public static native int globalUnlock(Address hMem);

    /** {@code WINBOOL ReadFile(HANDLE hFile, LPVOID lpBuffer, DWORD nNumberOfBytesToRead, LPDWORD lpNumberOfBytesRead, LPOVERLAPPED lpOverlapped)} - fileapi.h:206 */
    @Import(name = "ReadFile") public static native int readFile(Address hFile, Address lpBuffer, int nNumberOfBytesToRead, Address lpNumberOfBytesRead, Address lpOverlapped);

    /** {@code HMODULE LoadLibraryA(LPCSTR lpLibFileName)} - libloaderapi.h:103 */
    @Import(name = "LoadLibraryA") public static native Address loadLibraryA(Address lpLibFileName);

    /** {@code HMODULE LoadLibraryExA(LPCSTR lpLibFileName, HANDLE hFile, DWORD dwFlags)} - libloaderapi.h:170 */
    @Import(name = "LoadLibraryExA") public static native Address loadLibraryExA(Address lpLibFileName, Address hFile, int dwFlags);

    /** {@code FARPROC GetProcAddress(HMODULE hModule, LPCSTR lpProcName)} - libloaderapi.h:112 */
    @Import(name = "GetProcAddress") public static native Address getProcAddress(Address hModule, Address lpProcName);

    /** {@code HMODULE GetModuleHandleA(LPCSTR lpModuleName)} - libloaderapi.h:166 */
    @Import(name = "GetModuleHandleA") public static native Address getModuleHandleA(Address lpModuleName);

    /** {@code HANDLE GetCurrentProcess()} - processthreadsapi.h:302 */
    @Import(name = "GetCurrentProcess") public static native Address getCurrentProcess();

    /** {@code WINBOOL FreeLibrary(HMODULE hLibModule)} - libloaderapi.h:111 */
    @Import(name = "FreeLibrary") public static native int freeLibrary(Address hLibModule);

    /** {@code DWORD GetFinalPathNameByHandleA(HANDLE hFile, LPSTR lpszFilePath, DWORD cchFilePath, DWORD dwFlags)} - fileapi.h:149 */
    @Import(name = "GetFinalPathNameByHandleA") public static native int getFinalPathNameByHandleA(Address hFile, Address lpszFilePath, int cchFilePath, int dwFlags);

    /** {@code WINBOOL CreateProcessA(LPCSTR lpApplicationName, LPSTR lpCommandLine, LPSECURITY_ATTRIBUTES lpProcessAttributes, LPSECURITY_ATTRIBUTES lpThreadAttributes, WINBOOL bInheritHandles, DWORD dwCreationFlags, LPVOID lpEnvironment, LPCSTR lpCurrentDirectory, LPSTARTUPINFOA lpStartupInfo, LPPROCESS_INFORMATION lpProcessInformation)} - processthreadsapi.h:288 */
    @Import(name = "CreateProcessA") public static native int createProcessA(Address lpApplicationName, Address lpCommandLine, Address lpProcessAttributes, Address lpThreadAttributes, int bInheritHandles, int dwCreationFlags, Address lpEnvironment, Address lpCurrentDirectory, Address lpStartupInfo, Address lpProcessInformation);

    /** {@code DWORD WaitForSingleObject(HANDLE hHandle, DWORD dwMilliseconds)} - synchapi.h:115 */
    @Import(name = "WaitForSingleObject") public static native int waitForSingleObject(Address hHandle, int dwMilliseconds);

    /** {@code WINBOOL GetExitCodeProcess(HANDLE hProcess, LPDWORD lpExitCode)} - processthreadsapi.h:29 */
    @Import(name = "GetExitCodeProcess") public static native int getExitCodeProcess(Address hProcess, Address lpExitCode);

    /** {@code WINBOOL CloseHandle(HANDLE hObject)} - handleapi.h:19 */
    @Import(name = "CloseHandle") public static native int closeHandle(Address hObject);

    /** {@code int _open_osfhandle(intptr_t _OSFileHandle, int _Flags)} - io.h:178 */
    @Import(name = "_open_osfhandle") public static native int openOsfHandle(long _OSFileHandle, int _Flags);

    /** {@code int _dup2(int _FileHandleSrc, int _FileHandleDst)} - io.h:109 */
    @Import(name = "_dup2") public static native int dup2(int _FileHandleSrc, int _FileHandleDst);

    /** {@code int _close(int _FileHandle)} - io.h:105 */
    @Import(name = "_close") public static native int close(int _FileHandle);

    /** {@code intptr_t _get_osfhandle(int _FileHandle)} - io.h:177 */
    @Import(name = "_get_osfhandle") public static native long getOsfHandle(int _FileHandle);

    /** {@code HINTERNET WinHttpOpen(LPCWSTR, DWORD, LPCWSTR, LPCWSTR, DWORD)} - winhttp.h:915 */
    @Import(name = "WinHttpOpen") public static native Address winHttpOpen(Address lpcwstr, int dword, Address lpcwstr2, Address lpcwstr3, int dword2);

    /** {@code HINTERNET WinHttpConnect(HINTERNET, LPCWSTR, INTERNET_PORT, DWORD)} - winhttp.h:899 */
    @Import(name = "WinHttpConnect") public static native Address winHttpConnect(Address hinternet, Address lpcwstr, short internet_port, int dword);

    /** {@code HINTERNET WinHttpOpenRequest(HINTERNET, LPCWSTR, LPCWSTR, LPCWSTR, LPCWSTR, LPCWSTR *, DWORD)} - winhttp.h:916 */
    @Import(name = "WinHttpOpenRequest") public static native Address winHttpOpenRequest(Address hinternet, Address lpcwstr, Address lpcwstr2, Address lpcwstr3, Address lpcwstr4, Address arg5, int dword);

    /** {@code WINBOOL WinHttpSendRequest(HINTERNET, LPCWSTR, DWORD, LPVOID, DWORD, DWORD, DWORD_PTR)} - winhttp.h:926 */
    @Import(name = "WinHttpSendRequest") public static native int winHttpSendRequest(Address hinternet, Address lpcwstr, int dword, Address lpvoid, int dword2, int dword3, long dword_ptr);

    /** {@code WINBOOL WinHttpReceiveResponse(HINTERNET, LPVOID)} - winhttp.h:924 */
    @Import(name = "WinHttpReceiveResponse") public static native int winHttpReceiveResponse(Address hinternet, Address lpvoid);

    /** {@code WINBOOL WinHttpQueryHeaders(HINTERNET, DWORD, LPCWSTR, LPVOID, LPDWORD, LPDWORD)} - winhttp.h:920 */
    @Import(name = "WinHttpQueryHeaders") public static native int winHttpQueryHeaders(Address hinternet, int dword, Address lpcwstr, Address lpvoid, Address lpdword, Address lpdword2);

    /** {@code WINBOOL WinHttpQueryDataAvailable(HINTERNET, LPDWORD)} - winhttp.h:919 */
    @Import(name = "WinHttpQueryDataAvailable") public static native int winHttpQueryDataAvailable(Address hinternet, Address lpdword);

    /** {@code WINBOOL WinHttpReadData(HINTERNET, LPVOID, DWORD, LPDWORD)} - winhttp.h:922 */
    @Import(name = "WinHttpReadData") public static native int winHttpReadData(Address hinternet, Address lpvoid, int dword, Address lpdword);

    /** {@code WINBOOL WinHttpCloseHandle(HINTERNET)} - winhttp.h:898 */
    @Import(name = "WinHttpCloseHandle") public static native int winHttpCloseHandle(Address hinternet);

    /** {@code NTSTATUS BCryptOpenAlgorithmProvider(BCRYPT_ALG_HANDLE *phAlgorithm, LPCWSTR pszAlgId, LPCWSTR pszImplementation, ULONG dwFlags)} - bcrypt.h:762 */
    @Import(name = "BCryptOpenAlgorithmProvider") public static native int bCryptOpenAlgorithmProvider(Address phAlgorithm, Address pszAlgId, Address pszImplementation, int dwFlags);

    /** {@code NTSTATUS BCryptGetProperty(BCRYPT_HANDLE hObject, LPCWSTR pszProperty, PUCHAR pbOutput, ULONG cbOutput, ULONG *pcbResult, ULONG dwFlags)} - bcrypt.h:765 */
    @Import(name = "BCryptGetProperty") public static native int bCryptGetProperty(Address hObject, Address pszProperty, Address pbOutput, int cbOutput, Address pcbResult, int dwFlags);

    /** {@code NTSTATUS BCryptCreateHash(BCRYPT_ALG_HANDLE hAlgorithm, BCRYPT_HASH_HANDLE *phHash, PUCHAR pbHashObject, ULONG cbHashObject, PUCHAR pbSecret, ULONG cbSecret, ULONG dwFlags)} - bcrypt.h:785 */
    @Import(name = "BCryptCreateHash") public static native int bCryptCreateHash(Address hAlgorithm, Address phHash, Address pbHashObject, int cbHashObject, Address pbSecret, int cbSecret, int dwFlags);

    /** {@code NTSTATUS BCryptHashData(BCRYPT_HASH_HANDLE hHash, PUCHAR pbInput, ULONG cbInput, ULONG dwFlags)} - bcrypt.h:786 */
    @Import(name = "BCryptHashData") public static native int bCryptHashData(Address hHash, Address pbInput, int cbInput, int dwFlags);

    /** {@code NTSTATUS BCryptFinishHash(BCRYPT_HASH_HANDLE hHash, PUCHAR pbOutput, ULONG cbOutput, ULONG dwFlags)} - bcrypt.h:787 */
    @Import(name = "BCryptFinishHash") public static native int bCryptFinishHash(Address hHash, Address pbOutput, int cbOutput, int dwFlags);

    /** {@code NTSTATUS BCryptDestroyHash(BCRYPT_HASH_HANDLE hHash)} - bcrypt.h:793 */
    @Import(name = "BCryptDestroyHash") public static native int bCryptDestroyHash(Address hHash);

    /** {@code NTSTATUS BCryptCloseAlgorithmProvider(BCRYPT_ALG_HANDLE hAlgorithm, ULONG dwFlags)} - bcrypt.h:767 */
    @Import(name = "BCryptCloseAlgorithmProvider") public static native int bCryptCloseAlgorithmProvider(Address hAlgorithm, int dwFlags);

    /** {@code WINBOOL CreateDirectoryA(LPCSTR lpPathName, LPSECURITY_ATTRIBUTES lpSecurityAttributes)} - fileapi.h:191 */
    @Import(name = "CreateDirectoryA") public static native int createDirectoryA(Address lpPathName, Address lpSecurityAttributes);

    /** {@code WINBOOL RemoveDirectoryA(LPCSTR lpPathName)} - fileapi.h:207 */
    @Import(name = "RemoveDirectoryA") public static native int removeDirectoryA(Address lpPathName);

    /** {@code WINBOOL MoveFileExA(LPCSTR lpExistingFileName, LPCSTR lpNewFileName, DWORD dwFlags)} - winbase.h:2467 */
    @Import(name = "MoveFileExA") public static native int moveFileExA(Address lpExistingFileName, Address lpNewFileName, int dwFlags);

    /** {@code DWORD GetTempPathA(DWORD nBufferLength, LPSTR lpBuffer)} - fileapi.h:215 */
    @Import(name = "GetTempPathA") public static native int getTempPathA(int nBufferLength, Address lpBuffer);

    /** {@code UINT GetSystemDirectoryA(LPSTR lpBuffer, UINT uSize)} - sysinfoapi.h:123 */
    @Import(name = "GetSystemDirectoryA") public static native int getSystemDirectoryA(Address lpBuffer, int uSize);

    /** {@code WINBOOL SetFileAttributesA(LPCSTR lpFileName, DWORD dwFileAttributes)} - fileapi.h:210 */
    @Import(name = "SetFileAttributesA") public static native int setFileAttributesA(Address lpFileName, int dwFileAttributes);

    /** {@code WINBOOL InitCommonControlsEx(const INITCOMMONCONTROLSEX *)} - commctrl.h:74 */
    @Import(name = "InitCommonControlsEx") public static native int initCommonControlsEx(Address arg0);

    /** {@code HWND CreateWindowExA(DWORD dwExStyle, LPCSTR lpClassName, LPCSTR lpWindowName, DWORD dwStyle, int X, int Y, int nWidth, int nHeight, HWND hWndParent, HMENU hMenu, HINSTANCE hInstance, LPVOID lpParam)} - winuser.h:2203 */
    @Import(name = "CreateWindowExA") public static native Address createWindowExA(int dwExStyle, Address lpClassName, Address lpWindowName, int dwStyle, int X, int Y, int nWidth, int nHeight, Address hWndParent, Address hMenu, Address hInstance, Address lpParam);

    /** {@code UINT ExtractIconExW(LPCWSTR lpszFile, int nIconIndex, HICON *phiconLarge, HICON *phiconSmall, UINT nIcons)} - shellapi.h:151 */
    @Import(name = "ExtractIconExW") public static native int extractIconExW(Address lpszFile, int nIconIndex, Address phiconLarge, Address phiconSmall, int nIcons);

    /** {@code HMENU GetSystemMenu(HWND hWnd, WINBOOL bRevert)} - winuser.h:3277 */
    @Import(name = "GetSystemMenu") public static native Address getSystemMenu(Address hWnd, int bRevert);

    /** {@code WINBOOL EnableMenuItem(HMENU hMenu, UINT uIDEnableItem, UINT uEnable)} - winuser.h:3282 */
    @Import(name = "EnableMenuItem") public static native int enableMenuItem(Address hMenu, int uIDEnableItem, int uEnable);

    /** {@code WINBOOL DestroyIcon(HICON hIcon)} - winuser.h:4165 */
    @Import(name = "DestroyIcon") public static native int destroyIcon(Address hIcon);

    /** {@code WINBOOL DestroyWindow(HWND hWnd)} - winuser.h:2212 */
    @Import(name = "DestroyWindow") public static native int destroyWindow(Address hWnd);

    /** {@code WINBOOL UpdateWindow(HWND hWnd)} - winuser.h:3502 */
    @Import(name = "UpdateWindow") public static native int updateWindow(Address hWnd);

    /** {@code LRESULT SendMessageA(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam)} - winuser.h:2049 */
    @Import(name = "SendMessageA") public static native long sendMessageA(Address hWnd, int Msg, long wParam, long lParam);

    /** {@code WINBOOL PeekMessageA(LPMSG lpMsg, HWND hWnd, UINT wMsgFilterMin, UINT wMsgFilterMax, UINT wRemoveMsg)} - winuser.h:1973 */
    @Import(name = "PeekMessageA") public static native int peekMessageA(Address lpMsg, Address hWnd, int wMsgFilterMin, int wMsgFilterMax, int wRemoveMsg);

    /** {@code WINBOOL TranslateMessage(const MSG *lpMsg)} - winuser.h:1969 */
    @Import(name = "TranslateMessage") public static native int translateMessage(Address lpMsg);

    /** {@code LRESULT DispatchMessageA(const MSG *lpMsg)} - winuser.h:1970 */
    @Import(name = "DispatchMessageA") public static native long dispatchMessageA(Address lpMsg);

    /** {@code DWORD GetLastError()} - errhandlingapi.h:49 */
    @Import(name = "GetLastError") public static native int getLastError();

    /** {@code HANDLE BeginUpdateResourceW(LPCWSTR pFileName, WINBOOL bDeleteExistingResources)} - winbase.h:2052 */
    @Import(name = "BeginUpdateResourceW") public static native Address beginUpdateResourceW(Address pFileName, int bDeleteExistingResources);

    /** {@code WINBOOL UpdateResourceW(HANDLE hUpdate, LPCWSTR lpType, LPCWSTR lpName, WORD wLanguage, LPVOID lpData, DWORD cb)} - winbase.h:2054 */
    @Import(name = "UpdateResourceW") public static native int updateResourceW(Address hUpdate, Address lpType, Address lpName, short wLanguage, Address lpData, int cb);

    /** {@code WINBOOL EndUpdateResourceW(HANDLE hUpdate, WINBOOL fDiscard)} - winbase.h:2056 */
    @Import(name = "EndUpdateResourceW") public static native int endUpdateResourceW(Address hUpdate, int fDiscard);

    /** {@code HMODULE LoadLibraryExW(LPCWSTR lpLibFileName, HANDLE hFile, DWORD dwFlags)} - libloaderapi.h:171 */
    @Import(name = "LoadLibraryExW") public static native Address loadLibraryExW(Address lpLibFileName, Address hFile, int dwFlags);

    /** {@code HRSRC FindResourceExW(HMODULE hModule, LPCWSTR lpType, LPCWSTR lpName, WORD wLanguage)} - libloaderapi.h:165 */
    @Import(name = "FindResourceExW") public static native Address findResourceExW(Address hModule, Address lpType, Address lpName, short wLanguage);

    /** {@code HGLOBAL LoadResource(HMODULE hModule, HRSRC hResInfo)} - libloaderapi.h:73 */
    @Import(name = "LoadResource") public static native Address loadResource(Address hModule, Address hResInfo);

    /** {@code DWORD SizeofResource(HMODULE hModule, HRSRC hResInfo)} - libloaderapi.h:172 */
    @Import(name = "SizeofResource") public static native int sizeofResource(Address hModule, Address hResInfo);

    /** {@code LPVOID LockResource(HGLOBAL hResData)} - libloaderapi.h:74 */
    @Import(name = "LockResource") public static native Address lockResource(Address hResData);

    /** {@code WINBOOL EnumResourceNamesW(HMODULE hModule, LPCWSTR lpType, ENUMRESNAMEPROCW lpEnumFunc, LONG_PTR lParam)} - libloaderapi.h:71 */
    @Import(name = "EnumResourceNamesW") public static native int enumResourceNamesW(Address hModule, Address lpType, Address lpEnumFunc, long lParam);

    /** {@code WINBOOL EnumResourceLanguagesW(HMODULE hModule, LPCWSTR lpType, LPCWSTR lpName, ENUMRESLANGPROCW lpEnumFunc, LONG_PTR lParam)} - libloaderapi.h:85 */
    @Import(name = "EnumResourceLanguagesW") public static native int enumResourceLanguagesW(Address hModule, Address lpType, Address lpName, Address lpEnumFunc, long lParam);

    /** {@code WINBOOL EnumResourceTypesW(HMODULE hModule, ENUMRESTYPEPROCW lpEnumFunc, LONG_PTR lParam)} - winbase.h:2046 */
    @Import(name = "EnumResourceTypesW") public static native int enumResourceTypesW(Address hModule, Address lpEnumFunc, long lParam);

    /** {@code WINBOOL VerQueryValueW(LPCVOID pBlock, LPCWSTR lpSubBlock, LPVOID *lplpBuffer, PUINT puLen)} - winver.h:163 */
    @Import(name = "VerQueryValueW") public static native int verQueryValueW(Address pBlock, Address lpSubBlock, Address lplpBuffer, Address puLen);

    /** {@code WINBOOL WriteFile(HANDLE hFile, LPCVOID lpBuffer, DWORD nNumberOfBytesToWrite, LPDWORD lpNumberOfBytesWritten, LPOVERLAPPED lpOverlapped)} - fileapi.h:214 */
    @Import(name = "WriteFile") public static native int writeFile(Address hFile, Address lpBuffer, int nNumberOfBytesToWrite, Address lpNumberOfBytesWritten, Address lpOverlapped);

    /** {@code DWORD SetFilePointer(HANDLE hFile, LONG lDistanceToMove, PLONG lpDistanceToMoveHigh, DWORD dwMoveMethod)} - fileapi.h:33 */
    @Import(name = "SetFilePointer") public static native int setFilePointer(Address hFile, int lDistanceToMove, Address lpDistanceToMoveHigh, int dwMoveMethod);

    /** {@code WINBOOL GetFileSizeEx(HANDLE hFile, PLARGE_INTEGER lpFileSize)} - fileapi.h:78 */
    @Import(name = "GetFileSizeEx") public static native int getFileSizeEx(Address hFile, Address lpFileSize);

    /** {@code WINBOOL SetEndOfFile(HANDLE hFile)} - fileapi.h:209 */
    @Import(name = "SetEndOfFile") public static native int setEndOfFile(Address hFile);

    /** {@code WINBOOL CopyFileA(LPCSTR lpExistingFileName, LPCSTR lpNewFileName, WINBOOL bFailIfExists)} - winbase.h:2303 */
    @Import(name = "CopyFileA") public static native int copyFileA(Address lpExistingFileName, Address lpNewFileName, int bFailIfExists);

    /** {@code DWORD GetFullPathNameA(LPCSTR lpFileName, DWORD nBufferLength, LPSTR lpBuffer, LPSTR *lpFilePart)} - fileapi.h:81 */
    @Import(name = "GetFullPathNameA") public static native int getFullPathNameA(Address lpFileName, int nBufferLength, Address lpBuffer, Address lpFilePart);

    /** {@code HCERTSTORE CertOpenStore(LPCSTR lpszStoreProvider, DWORD dwEncodingType, HCRYPTPROV_LEGACY hCryptProv, DWORD dwFlags, const void *pvPara)} - wincrypt.h:3976 */
    @Import(name = "CertOpenStore") public static native Address certOpenStore(Address lpszStoreProvider, int dwEncodingType, long hCryptProv, int dwFlags, Address pvPara);

    /** {@code PCCERT_CONTEXT CertFindCertificateInStore(HCERTSTORE hCertStore, DWORD dwCertEncodingType, DWORD dwFindFlags, DWORD dwFindType, const void *pvFindPara, PCCERT_CONTEXT pPrevCertContext)} - wincrypt.h:4081 */
    @Import(name = "CertFindCertificateInStore") public static native Address certFindCertificateInStore(Address hCertStore, int dwCertEncodingType, int dwFindFlags, int dwFindType, Address pvFindPara, Address pPrevCertContext);

    /** {@code WINBOOL CertCloseStore(HCERTSTORE hCertStore, DWORD dwFlags)} - wincrypt.h:4078 */
    @Import(name = "CertCloseStore") public static native int certCloseStore(Address hCertStore, int dwFlags);

    /** {@code PCCERT_CONTEXT CertEnumCertificatesInStore(HCERTSTORE hCertStore, PCCERT_CONTEXT pPrevCertContext)} - wincrypt.h:4080 */
    @Import(name = "CertEnumCertificatesInStore") public static native Address certEnumCertificatesInStore(Address hCertStore, Address pPrevCertContext);

    /** {@code WINBOOL CertFreeCertificateContext(PCCERT_CONTEXT pCertContext)} - wincrypt.h:4159 */
    @Import(name = "CertFreeCertificateContext") public static native int certFreeCertificateContext(Address pCertContext);

    /** {@code WINBOOL CryptAcquireCertificatePrivateKey(PCCERT_CONTEXT pCert, DWORD dwFlags, void *pvParameters, HCRYPTPROV_OR_NCRYPT_KEY_HANDLE *phCryptProvOrNCryptKey, DWORD *pdwKeySpec, WINBOOL *pfCallerFreeProvOrNCryptKey)} - wincrypt.h:4584 */
    @Import(name = "CryptAcquireCertificatePrivateKey") public static native int cryptAcquireCertificatePrivateKey(Address pCert, int dwFlags, Address pvParameters, Address phCryptProvOrNCryptKey, Address pdwKeySpec, Address pfCallerFreeProvOrNCryptKey);

    /** {@code HCERTSTORE PFXImportCertStore(CRYPT_DATA_BLOB *pPFX, LPCWSTR szPassword, DWORD dwFlags)} - wincrypt.h:5695 */
    @Import(name = "PFXImportCertStore") public static native Address pfxImportCertStore(Address pPFX, Address szPassword, int dwFlags);

    /** {@code DWORD CertGetNameStringW(PCCERT_CONTEXT pCertContext, DWORD dwType, DWORD dwFlags, void *pvTypePara, LPWSTR pszNameString, DWORD cchNameString)} - wincrypt.h:4621 */
    @Import(name = "CertGetNameStringW") public static native int certGetNameStringW(Address pCertContext, int dwType, int dwFlags, Address pvTypePara, Address pszNameString, int cchNameString);

    /** {@code HRESULT SignerSignEx2(DWORD dwFlags, SIGNER_SUBJECT_INFO *pSubjectInfo, SIGNER_CERT *pSignerCert, SIGNER_SIGNATURE_INFO *pSignatureInfo, void *pProviderInfo, DWORD dwTimestampFlags, PCSTR pszTimestampAlgorithmOid, PCWSTR pwszTimestampURL, PCRYPT_ATTRIBUTES psRequest, void *pSipData, SIGNER_CONTEXT **ppSignerContext, void *pCryptoPolicy, void *pReserved)} - mssign.h:55 */
    @Import(name = "SignerSignEx2") public static native int signerSignEx2(int dwFlags, Address pSubjectInfo, Address pSignerCert, Address pSignatureInfo, Address pProviderInfo, int dwTimestampFlags, Address pszTimestampAlgorithmOid, Address pwszTimestampURL, Address psRequest, Address pSipData, Address ppSignerContext, Address pCryptoPolicy, Address pReserved);

    /** {@code HRESULT SignerFreeSignerContext(SIGNER_CONTEXT *pSignerContext)} - mssign.h:60 */
    @Import(name = "SignerFreeSignerContext") public static native int signerFreeSignerContext(Address pSignerContext);

    public static final int MB_ICONERROR = 16; // long, winuser.h:3687
    public static final int MB_ICONINFORMATION = 64; // long, winuser.h:3688
    public static final int MB_ICONQUESTION = 32; // long, winuser.h:3682
    public static final int MB_YESNO = 4; // long, winuser.h:3678
    public static final int IDYES = 6; // int, winuser.h:4371
    public static final int MB_OKCANCEL = 1; // long, winuser.h:3675
    public static final int IDOK = 1; // int, winuser.h:4366
    public static final int CF_UNICODETEXT = 13; // int, winuser.h:1784
    public static final int GMEM_MOVEABLE = 2; // int, winbase.h:377
    public static final int STD_INPUT_HANDLE = -10; // unsigned long, winbase.h:503
    public static final int STD_OUTPUT_HANDLE = -11; // unsigned long, winbase.h:504
    public static final int STD_ERROR_HANDLE = -12; // unsigned long, winbase.h:505
    public static final int INVALID_FILE_ATTRIBUTES = -1; // unsigned long, fileapi.h:26
    public static final Address INVALID_HANDLE_VALUE = Address.fromLong(-1L); // void*, handleapi.h:16
    public static final int SW_HIDE = 0; // int, winuser.h:200
    public static final int SW_SHOWNORMAL = 1; // int, winuser.h:201
    public static final int SW_SHOW = 5; // int, winuser.h:207
    public static final int ATTACH_PARENT_PROCESS = -1; // unsigned long, consoleapi.h:57
    public static final int GENERIC_READ = 0x80000000; // unsigned long, winnt.h:3165
    public static final int GENERIC_WRITE = 0x40000000; // long, winnt.h:3166
    public static final int FILE_SHARE_READ = 1; // int, winnt.h:6166
    public static final int FILE_SHARE_WRITE = 2; // int, winnt.h:6167
    public static final int OPEN_EXISTING = 3; // int, fileapi.h:20
    public static final int LOAD_WITH_ALTERED_SEARCH_PATH = 8; // int, libloaderapi.h:143
    public static final int INFINITE = -1; // unsigned int, winbase.h:518
    public static final int FILE_FLAG_BACKUP_SEMANTICS = 0x02000000; // int, winbase.h:90
    public static final int FILE_SHARE_DELETE = 4; // int, winnt.h:6168
    public static final int WINHTTP_ACCESS_TYPE_DEFAULT_PROXY = 0; // int, winhttp.h:71
    public static final int WINHTTP_FLAG_SECURE = 0x00800000; // int, winhttp.h:69
    public static final int WINHTTP_QUERY_CONTENT_LENGTH = 5; // int, winhttp.h:418
    public static final int WINHTTP_QUERY_FLAG_NUMBER = 0x20000000; // int, winhttp.h:492
    public static final int WINHTTP_QUERY_STATUS_CODE = 19; // int, winhttp.h:432
    public static final int MOVEFILE_COPY_ALLOWED = 2; // int, winbase.h:2489
    public static final int FILE_ATTRIBUTE_NORMAL = 128; // int, winnt.h:6176
    public static final int CREATE_NO_WINDOW = 0x08000000; // int, winbase.h:440
    public static final int WS_CAPTION = 0x00C00000; // long, winuser.h:1589
    public static final int WS_SYSMENU = 0x00080000; // long, winuser.h:1594
    public static final int WM_SETICON = 128; // int, winuser.h:1146
    public static final int ICON_SMALL = 0; // int, winuser.h:1496
    public static final int ICON_BIG = 1; // int, winuser.h:1497
    public static final int SC_CLOSE = 0x0000F060; // int, winuser.h:4083
    public static final int MF_BYCOMMAND = 0; // long, winuser.h:4015
    public static final int MF_GRAYED = 1; // long, winuser.h:4019
    public static final int WS_CHILD = 0x40000000; // long, winuser.h:1582
    public static final int WS_VISIBLE = 0x10000000; // long, winuser.h:1584
    public static final int WS_EX_TOPMOST = 8; // long, winuser.h:1611
    public static final int CW_USEDEFAULT = 0x80000000; // int, winuser.h:2169
    public static final int ICC_PROGRESS_CLASS = 32; // int, commctrl.h:61
    public static final int PBM_SETRANGE = 1025; // int, commctrl.h:2126
    public static final int PBM_SETPOS = 1026; // int, commctrl.h:2127
    public static final int PM_REMOVE = 1; // int, winuser.h:1978
    public static final int LOAD_LIBRARY_AS_DATAFILE = 2; // int, libloaderapi.h:142
    public static final int LOAD_LIBRARY_AS_IMAGE_RESOURCE = 32; // int, libloaderapi.h:145
    public static final int FILE_BEGIN = 0; // int, winbase.h:69
    public static final int IMAGE_DOS_SIGNATURE = 0x00005A4D; // int, winnt.h:7428
    public static final int IMAGE_NT_SIGNATURE = 0x00004550; // int, winnt.h:7432
    public static final int IMAGE_NT_OPTIONAL_HDR32_MAGIC = 267; // int, winnt.h:7704
    public static final int IMAGE_NT_OPTIONAL_HDR64_MAGIC = 523; // int, winnt.h:7705
    public static final int IMAGE_DIRECTORY_ENTRY_SECURITY = 4; // int, winnt.h:7778
    public static final Address CERT_STORE_PROV_SYSTEM_W = Address.fromLong(10L); // char*, wincrypt.h:3760
    public static final int CERT_SYSTEM_STORE_CURRENT_USER = 0x00010000; // int, wincrypt.h:3852
    public static final int CERT_SYSTEM_STORE_LOCAL_MACHINE = 0x00020000; // int, wincrypt.h:3853
    public static final int CERT_STORE_READONLY_FLAG = 0x00008000; // int, wincrypt.h:3815
    public static final int CERT_FIND_HASH = 0x00010000; // int, wincrypt.h:4115
    public static final int X509_ASN_ENCODING = 1; // int, wincrypt.h:1445
    public static final int PKCS_7_ASN_ENCODING = 0x00010000; // int, wincrypt.h:1447
    public static final int PKCS12_NO_PERSIST_KEY = 0x00008000; // int, wincrypt.h:5707
    public static final int PKCS12_ALWAYS_CNG_KSP = 512; // int, wincrypt.h:5703
    public static final int CRYPT_ACQUIRE_CACHE_FLAG = 1; // int, wincrypt.h:4550
    public static final int CRYPT_ACQUIRE_ALLOW_NCRYPT_KEY_FLAG = 0x00010000; // int, wincrypt.h:4558
    public static final int CRYPT_ACQUIRE_SILENT_FLAG = 64; // int, wincrypt.h:4554
    public static final int CERT_NAME_SIMPLE_DISPLAY_TYPE = 4; // int, wincrypt.h:4626
    public static final int CALG_SHA_256 = 0x0000800C; // int, wincrypt.h:248
    public static final int VS_FFI_FILEFLAGSMASK = 63; // long, winver.h:23
    public static final int VOS_NT_WINDOWS32 = 0x00040004; // long, winver.h:49
    public static final int VFT_APP = 1; // long, winver.h:52
    public static final Address RT_ICON = Address.fromLong(3L); // char*, winuser.h:125
    public static final Address RT_GROUP_ICON = Address.fromLong(14L); // char*, winuser.h:137
    public static final Address RT_VERSION = Address.fromLong(16L); // char*, winuser.h:138
    public static final Address RT_MANIFEST = Address.fromLong(24L); // char*, winuser.h:154
    public static final Address RT_RCDATA = Address.fromLong(10L); // char*, winuser.h:132
    public static final Address RT_HTML = Address.fromLong(23L); // char*, winuser.h:144
    public static final Address RT_STRING = Address.fromLong(6L); // char*, winuser.h:128
    public static final int VS_VERSION_INFO = 1; // int, winver.h:18
    public static final int STARTF_USESTDHANDLES = 256; // int, winbase.h:1574
    public static final int FILE_ATTRIBUTE_DIRECTORY = 16; // int, winnt.h:6173
    public static final int MAX_PATH = 260; // int, minwindef.h:33
    public static final int IMAGE_FILE_MACHINE_ARM64 = 0x0000AA64; // int, winnt.h:7590
    public static final int GET_FILEEX_INFO_STANDARD = 0; // int, minwinbase.h:136
    public static final String BCRYPT_SHA256_ALGORITHM = "SHA256"; // wide L"" literal (pass via Wstr), unsigned short*, bcrypt.h:352
    public static final String BCRYPT_OBJECT_LENGTH = "ObjectLength"; // wide L"" literal (pass via Wstr), unsigned short*, bcrypt.h:135
    public static final String BCRYPT_HASH_LENGTH = "HashDigestLength"; // wide L"" literal (pass via Wstr), unsigned short*, bcrypt.h:125
    /** {@code LONG RegOpenKeyExA(HKEY hKey, LPCSTR lpSubKey, DWORD ulOptions, REGSAM samDesired, PHKEY phkResult)} - winreg.h:417 */
    @Import(name = "RegOpenKeyExA") public static native int regOpenKeyExA(Address hKey, Address lpSubKey, int ulOptions, int samDesired, Address phkResult);

    /** {@code LONG RegEnumKeyExA(HKEY hKey, DWORD dwIndex, LPSTR lpName, LPDWORD lpcchName, LPDWORD lpReserved, LPSTR lpClass, LPDWORD lpcchClass, PFILETIME lpftLastWriteTime)} - winreg.h:410 */
    @Import(name = "RegEnumKeyExA") public static native int regEnumKeyExA(Address hKey, int dwIndex, Address lpName, Address lpcchName, Address lpReserved, Address lpClass, Address lpcchClass, Address lpftLastWriteTime);

    /** {@code LONG RegQueryValueExA(HKEY hKey, LPCSTR lpValueName, LPDWORD lpReserved, LPDWORD lpType, LPBYTE lpData, LPDWORD lpcbData)} - winreg.h:421 */
    @Import(name = "RegQueryValueExA") public static native int regQueryValueExA(Address hKey, Address lpValueName, Address lpReserved, Address lpType, Address lpData, Address lpcbData);

    /** {@code LONG RegCloseKey(HKEY hKey)} - winreg.h:403 */
    @Import(name = "RegCloseKey") public static native int regCloseKey(Address hKey);

    /** {@code DWORD GetFileVersionInfoSizeA(LPCSTR lptstrFilename, LPDWORD lpdwHandle)} - winver.h:149 */
    @Import(name = "GetFileVersionInfoSizeA") public static native int getFileVersionInfoSizeA(Address lptstrFilename, Address lpdwHandle);

    /** {@code WINBOOL GetFileVersionInfoA(LPCSTR lptstrFilename, DWORD dwHandle, DWORD dwLen, LPVOID lpData)} - winver.h:153 */
    @Import(name = "GetFileVersionInfoA") public static native int getFileVersionInfoA(Address lptstrFilename, int dwHandle, int dwLen, Address lpData);

    public static final Address HKEY_LOCAL_MACHINE = Address.fromLong(-2147483646L); // void*, winreg.h:48
    public static final Address HKEY_CURRENT_USER = Address.fromLong(-2147483647L); // void*, winreg.h:47
    public static final int KEY_READ = 0x00020019; // long, winnt.h:9986
    public static final int KEY_WOW64_64KEY = 256; // int, winnt.h:9982
    public static final int ERROR_SUCCESS = 0; // long, winerror.h:167
    public static final int IMAGE_FILE_MACHINE_AMD64 = 0x00008664; // int, winnt.h:7604
    public static final int IMAGE_FILE_MACHINE_I386 = 332; // int, winnt.h:7576
    /** {@code WINBOOL SetHandleInformation(HANDLE hObject, DWORD dwMask, DWORD dwFlags)} - handleapi.h:28 */
    @Import(name = "SetHandleInformation") public static native int setHandleInformation(Address hObject, int dwMask, int dwFlags);

    /** {@code WINBOOL GetConsoleScreenBufferInfo(HANDLE console_output, PCONSOLE_SCREEN_BUFFER_INFO console_screen_buffer_info)} - consoleapi2.h:72 */
    @Import(name = "GetConsoleScreenBufferInfo") public static native int getConsoleScreenBufferInfo(Address console_output, Address console_screen_buffer_info);

    /** {@code HANDLE CreateFileW(LPCWSTR lpFileName, DWORD dwDesiredAccess, DWORD dwShareMode, LPSECURITY_ATTRIBUTES lpSecurityAttributes, DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes, HANDLE hTemplateFile)} - fileapi.h:64 */
    @Import(name = "CreateFileW") public static native Address createFileW(Address lpFileName, int dwDesiredAccess, int dwShareMode, Address lpSecurityAttributes, int dwCreationDisposition, int dwFlagsAndAttributes, Address hTemplateFile);

    /** {@code ULONGLONG GetTickCount64()} - sysinfoapi.h:42 */
    @Import(name = "GetTickCount64") public static native long getTickCount64();

    public static final int HANDLE_FLAG_INHERIT = 1; // int, winbase.h:1355
    public static final int CREATE_ALWAYS = 2; // int, fileapi.h:19
    public static final int WAIT_TIMEOUT = 258; // long, winerror.h:356
    /** {@code #define JX_ReadConsoleOutputCharacterA(5 arguments)} - a function-like macro, expanded by the C compiler at the call; result: int, 4 bytes, per clang */
    @Import(name = "JX_ReadConsoleOutputCharacterA") public static native int readConsoleOutputCharacterA(Address arg0, Address arg1, int arg2, Address arg3, Address arg4);

    /** {@code int atexit(void (*)(void) __attribute__((cdecl)))} - stdlib.h:273 */
    @Import(name = "atexit") public static native int atexit(Address arg0);

    /** {@code void ExitProcess(UINT uExitCode)} - processthreadsapi.h:28 */
    @Import(name = "ExitProcess") public static native void exitProcess(int uExitCode);

    /** {@code HINSTANCE ShellExecuteW(HWND hwnd, LPCWSTR lpOperation, LPCWSTR lpFile, LPCWSTR lpParameters, LPCWSTR lpDirectory, INT nShowCmd)} - shellapi.h:76 */
    @Import(name = "ShellExecuteW") public static native Address shellExecuteW(Address hwnd, Address lpOperation, Address lpFile, Address lpParameters, Address lpDirectory, int nShowCmd);

    /** {@code WINBOOL SetWindowTextW(HWND hWnd, LPCWSTR lpString)} - winuser.h:3638 */
    @Import(name = "SetWindowTextW") public static native int setWindowTextW(Address hWnd, Address lpString);

    /** {@code int GetWindowTextW(HWND hWnd, LPWSTR lpString, int nMaxCount)} - winuser.h:3640 */
    @Import(name = "GetWindowTextW") public static native int getWindowTextW(Address hWnd, Address lpString, int nMaxCount);

    /** {@code int GetWindowTextLengthW(HWND hWnd)} - winuser.h:3642 */
    @Import(name = "GetWindowTextLengthW") public static native int getWindowTextLengthW(Address hWnd);

    /** {@code WINBOOL SetWindowTextA(HWND hWnd, LPCSTR lpString)} - winuser.h:3637 */
    @Import(name = "SetWindowTextA") public static native int setWindowTextA(Address hWnd, Address lpString);

    /** {@code WINBOOL IsDialogMessageW(HWND hDlg, LPMSG lpMsg)} - winuser.h:4618 */
    @Import(name = "IsDialogMessageW") public static native int isDialogMessageW(Address hDlg, Address lpMsg);

    /** {@code HWND SetFocus(HWND hWnd)} - winuser.h:2576 */
    @Import(name = "SetFocus") public static native Address setFocus(Address hWnd);

    /** {@code WINBOOL IsChild(HWND hWndParent, HWND hWnd)} - winuser.h:2211 */
    @Import(name = "IsChild") public static native int isChild(Address hWndParent, Address hWnd);

    /** {@code WINBOOL IsWindowVisible(HWND hWnd)} - winuser.h:2307 */
    @Import(name = "IsWindowVisible") public static native int isWindowVisible(Address hWnd);

    /** {@code WINBOOL SetForegroundWindow(HWND hWnd)} - winuser.h:3507 */
    @Import(name = "SetForegroundWindow") public static native int setForegroundWindow(Address hWnd);

    /** {@code DWORD MsgWaitForMultipleObjects(DWORD nCount, const HANDLE *pHandles, WINBOOL fWaitAll, DWORD dwMilliseconds, DWORD dwWakeMask)} - winuser.h:2989 */
    @Import(name = "MsgWaitForMultipleObjects") public static native int msgWaitForMultipleObjects(int nCount, Address pHandles, int fWaitAll, int dwMilliseconds, int dwWakeMask);

    /** {@code HGDIOBJ GetStockObject(int i)} - wingdi.h:3086 */
    @Import(name = "GetStockObject") public static native Address getStockObject(int i);

    /** {@code void GetSystemTimeAsFileTime(LPFILETIME lpSystemTimeAsFileTime)} - sysinfoapi.h:38 */
    @Import(name = "GetSystemTimeAsFileTime") public static native void getSystemTimeAsFileTime(Address lpSystemTimeAsFileTime);

    public static final int ES_MULTILINE = 4; // long, winuser.h:4388
    public static final int ES_AUTOVSCROLL = 64; // long, winuser.h:4392
    public static final int ES_WANTRETURN = 4096; // long, winuser.h:4397
    public static final int WS_VSCROLL = 0x00200000; // long, winuser.h:1592
    public static final int WS_BORDER = 0x00800000; // long, winuser.h:1590
    public static final int WS_TABSTOP = 0x00010000; // long, winuser.h:1597
    public static final int WS_EX_CLIENTEDGE = 512; // long, winuser.h:1617
    public static final int BS_PUSHBUTTON = 0; // long, winuser.h:4479
    public static final int WM_KEYDOWN = 256; // int, winuser.h:1175
    public static final int WM_LBUTTONUP = 514; // int, winuser.h:1240
    public static final int WM_LBUTTONDOWN = 513; // int, winuser.h:1239
    public static final int WM_NCLBUTTONDOWN = 161; // int, winuser.h:1159
    public static final int WM_SETFONT = 48; // int, winuser.h:1090
    public static final int HTCLOSE = 20; // int, winuser.h:1479
    public static final int VK_ESCAPE = 27; // int, winuser.h:271
    public static final int VK_RETURN = 13; // int, winuser.h:256
    public static final int VK_SPACE = 32; // int, winuser.h:276
    public static final int VK_F2 = 113; // int, winuser.h:314
    public static final int VK_F3 = 114; // int, winuser.h:315
    public static final int VK_F4 = 115; // int, winuser.h:316
    public static final int VK_F5 = 116; // int, winuser.h:317
    public static final int VK_F6 = 117; // int, winuser.h:318
    public static final int VK_F7 = 118; // int, winuser.h:319
    public static final int DEFAULT_GUI_FONT = 17; // int, wingdi.h:1458
    public static final int QS_ALLINPUT = 1279; // int, winuser.h:3027
    public static final int FILE_APPEND_DATA = 4; // int, winnt.h:6116
    public static final int OPEN_ALWAYS = 4; // int, fileapi.h:21
    /** {@code WINBOOL SystemParametersInfoW(UINT uiAction, UINT uiParam, PVOID pvParam, UINT fWinIni)} - winuser.h:5636 */
    @Import(name = "SystemParametersInfoW") public static native int systemParametersInfoW(int uiAction, int uiParam, Address pvParam, int fWinIni);

    /** {@code HFONT CreateFontIndirectW(const LOGFONTW *lplf)} - wingdi.h:2901 */
    @Import(name = "CreateFontIndirectW") public static native Address createFontIndirectW(Address lplf);

    /** {@code HDC GetDC(HWND hWnd)} - winuser.h:3511 */
    @Import(name = "GetDC") public static native Address getDC(Address hWnd);

    /** {@code int ReleaseDC(HWND hWnd, HDC hDC)} - winuser.h:3550 */
    @Import(name = "ReleaseDC") public static native int releaseDC(Address hWnd, Address hDC);

    /** {@code int GetDeviceCaps(HDC hdc, int index)} - wingdi.h:3051 */
    @Import(name = "GetDeviceCaps") public static native int getDeviceCaps(Address hdc, int index);

    public static final int LOGPIXELSY = 90; // int, wingdi.h:1539
    public static final int SPI_GETNONCLIENTMETRICS = 41; // int, winuser.h:5099
    /** {@code int GetSystemMetrics(int nIndex)} - winuser.h:3192 */
    @Import(name = "GetSystemMetrics") public static native int getSystemMetrics(int nIndex);

    public static final int SM_CXSMICON = 49; // int, winuser.h:3128
    public static final int SM_CXICON = 11; // int, winuser.h:3084
}
